### ISSUE TITLE
Scylla boots considerably slower with Raft

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10055]
I noticed that booting a single-node Scylla is considerably slower when `--experimental-features=raft` is enabled. For example on my laptop in dev build:

```
$ test/cql-pytest/run nothing
...
Boot successful (0.3 seconds).
...

$ test/cql-pytest/run --raft nothing
...
Boot successful (2.1 seconds).
...
```

`test/cql-pytest/run` start Scylla and prints the time until the CQL protocol is usable. As you can see passing `--experimental-features=raft` to Scylla (this is what the "--raft" option does) adds as much as 1.8 seconds to the boot (and makes it 7 times slower).

It seems that most of this extra slowdown happens as a one-time delay, as we can see in the log:
```
INFO  2022-02-09 14:39:06,305 [shard 0] raft_group_registry - 69cee987-d7bb-45cc-a01f-88ad9bda79c4 joined group 0 with id 45118cf0-89a5-11ec-86d4-a4afeb54a1b8
INFO  2022-02-09 14:39:06,305 [shard 0] storage_service - I am the first node in the cluster. Skip bootstrap. Node=127.5.233.186
INFO  2022-02-09 14:39:06,305 [shard 0] init - starting system distributed keyspace
INFO  2022-02-09 14:39:07,907 [shard 0] schema_tables - Creating keyspace system_distributed
```
Note that there is a 1.6 second delay between the last two messages. What happens during this time?

**Comment by gleb-cloudius** [comment]
A leader needs to be elected. It takes time.

**Comment by kostja** [comment]
We could elect leader automatically in start() if this is a single server.

**Comment by nyh** [comment]
> A leader needs to be elected. It takes time.

Since there is just one server in the cluster, what exactly happens during that time? If I understand correctly, the first node in the cluster knows that it is the first node, right? So it doesn't actually need to wait for anything?

Also, is the extra 1.6-second delay that I'm seeing is CPU time spent doing some computations, or sleeps? If it's sleeps, could we add an option to configure them, especially for tests? Although even for non-test deployments, I'm not enthusiastic about every developer adding more and more sleeps during boot.

**Comment by kostja** [comment]
We let the server which starts in the follower state to time out before it becomes a candidate.

**Comment by nyh** [comment]
> We let the server which starts in the follower state to time out before it becomes a candidate.

Who does the first server follow?
Even if you don't want to short-circuit the election process and just elect itself, why does the first server need to time out? What might go wrong if the first server **immediately** makes itself a candidate? 

If I understand correctly, the reason for the random sleep before proposing yourself is to prevent the thundering herd problem (100 nodes propose themselves at the same time). BUT, if we only allow this immediate-proposal-without-timeout **once, during boot**, this problem cannot happen - because we are not realistically worried about 100 nodes booting at the same time - we're worried that this thundering herd happens during normal operation.

**Comment by kostja** [comment]
@nyh that's exactly what I wrote in https://github.com/scylladb/scylla/issues/10055#issuecomment-1055524811

**Comment by nyh** [comment]
@kostja yes, my first paragraph is the same as you proposed, but the second paragraph is even more general and doesn't require us to know if we're the "first" server or not (I assume we know, but maybe we don't?). My proposal in the second paragraph is that any server could propose itself as candidate when it boots, immediately without any wait. The risk of 100 nodes doing this together would hopefully be minimal.

I don't know which of the two proposals is better, I'll let you decide as obviously you are much more familiar in this area of the code than I am.

By the way, it's worth checking what happens when we already have a cluster and adding a new node. Can it just "adopt" the existing leader immediately and decide not to propose itself, or does the code today also sleep and then propose itself even though there is a leader already? I didn't check this case because I was only interested in the single-node case, but obviously on real cluster the many-node case is more common.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 01, 2022 at 06:50:27AM -0800, Konstantin Osipov wrote:
> We could elect leader automatically in start() if this is a single server.
> 
Well, I tried to set election timeout to minimum in start() if there is
only one node in a config, but nemesis test fails. Probably because it
reuses nodes during topology change without resetting their states.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
Fixed by 108e7fcc4ea700eed1f94b203f75317ac15a1bfc

**Comment by nyh** [comment]
Thanks. I can confirm it did bring back the single-node boot to be as fast as it was without raft.

But I still don't understand what happens when we boot several nodes in sequence. The first node will, after this patch, immediately nominate itself, which is great. When the second node boots, will it recognize the existing leader immediately - or will it have this 2-second timeout during start?

I hope it's the former (the second node will recognize the existing leader immediately), not the latter (2 second wait). Because multi-node boot time is also important for dtests: For many years, we were "convinced" that multi-node boots can't be fast, and that it makes sense for dtest to take two minutes to boot a 5-node cluster. But in https://github.com/scylladb/scylla-dtest/pull/2455 I showed that this assumption is poppycock - dtest can be fixed to boot a 5-node cluster in 9 seconds (!), or perhaps even less if we continue working on it. At that point, becomes important that Raft doesn't add  another 2 seconds to each node's boot.
