### ISSUE TITLE
Write only workload which is throttled and uses only 20-30% CPU can't be sustained

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#10704]
5.0.rc6

Setup 

1. start an i3.large with 5.0.rc6
2.  start cassandra stress throttled at 2K op/sec
```
cassandra-stress write n=100000000 cl=quorum -node  172.31.129.87 -mode native cql3 user=cassandra password=.... -schema "replication(strategy=SimpleStrategy,replication_factor=1)" keyspace="keyspace5" -col size=FIXED\(2048\) -errors ignore -rate threads=50  throttle=2000/s
```

![Screenshot from 2022-05-31 17-23-54](https://user-images.githubusercontent.com/3465480/171197815-74b5a7a2-7aec-4687-8753-5a4f6e67fe98.png)
![Screenshot from 2022-05-31 17-24-01](https://user-images.githubusercontent.com/3465480/171197876-fafc9b06-33aa-4a39-a6e6-71541eceb214.png)

![Screenshot from 2022-05-31 17-25-11](https://user-images.githubusercontent.com/3465480/171197586-148df8d2-fca4-4236-8014-624d3479f198.png)
![Screenshot from 2022-05-31 17-24-56](https://user-images.githubusercontent.com/3465480/171197593-7d3d6d91-5514-4a56-ae28-4ccecf2daccb.png)
![Screenshot from 2022-05-31 17-24-44](https://user-images.githubusercontent.com/3465480/171197604-6c998ebd-dc54-4b4d-acc2-6bda36ba372a.png)

Comparing this to 4.6.3 this is a regression 4.6.3 can sustain the workload  over time 

![Screenshot from 2022-05-31 17-47-53](https://user-images.githubusercontent.com/3465480/171202613-b53f922f-b8f1-4157-82f2-fa81479c67a1.png)
![Screenshot from 2022-05-31 17-47-46](https://user-images.githubusercontent.com/3465480/171202619-64e45b93-c357-4e55-aade-814bda8376cc.png)

The issue maybe related to io scheduler - could it be that we provide compaction all the bandwidth not leaving commitlog "enough" bandwidth to sustain a constant pace of commitlog writting.

**Comment by slivne** [comment]
I am not sure what is the commitlog priority/scheduling group ?

**Comment by xemul** [comment]
@slivne , is there AMI available that includes the fix?

**Comment by xemul** [comment]
Note, that commitlog bandwidth is ~10MB/s and IOPS is ~100. This gives ~102kB request size, while on i3.xl the IO queue would recommend 80kB maximum request size.

**Comment by slivne** [comment]
maybe we do we have ami-02746c2610b5651e2 from https://jenkins.scylladb.com/view/master/job/scylla-master/job/ami/944/ which is based on 4c3678e2a058 which seems to include avi's fix in c83393e8197a1183fbb94e167bc68f6e70e87174.

The only gotcha is that I did not try and run it

**Comment by slivne** [comment]
not sure where you are running the tests - https://jenkins.scylladb.com/view/master/job/scylla-master/job/ami/944/console has the full info at the end

**Comment by slivne** [comment]
@xemul ^^

**Comment by slivne** [comment]
@xemul any luck ?

**Comment by xemul** [comment]
@slivne , sorry. On ami-02746c2610b5651e2 it all went very smooth. 
![cs-stats-10704](https://user-images.githubusercontent.com/4498177/172153707-be498c42-8612-4599-802a-cba71acd5538.png)
![io-stats-10704](https://user-images.githubusercontent.com/4498177/172153711-a072abbe-c00d-4652-87f9-8b6abdf25a1f.png)

**Comment by avikivity** [comment]
c89117e5f75846c1ee5c236f424260608b3eda6a contains an I/O scheduler change, but should not change performance IIUC.

**Comment by avikivity** [comment]
Could also be a kernel update.

**Comment by slivne** [comment]
The commit c89117e5f75846c1ee5c236f424260608b3eda6a is ok 

Tring the one before 44e9e1041461ac513ab5f010786b35f0d89921a3

**Comment by slivne** [comment]
https://github.com/scylladb/scylla/commit/44e9e1041461ac513ab5f010786b35f0d89921a3

on 

```
Linux ip-172-31-242-121 5.13.0-1021-aws #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

behaves bad

something in the seastar patch causes scylla to behave better

@xemul - please take it from here and bisect - we can also try and simply apply this change ontop of rc6 and see if this fixes the issue.

**Comment by slivne** [comment]
To make it clear - the patch https://github.com/scylladb/scylla/commit/c89117e5f75846c1ee5c236f424260608b3eda6a fixes an issue in scylla.


The workload I used to test scylla is 

scylla running on i3.large
loader running on c5.4xlarge with workload

```
cassandra-stress write n=100000000 cl=quorum -node 172.31.242.121 -mode native cql3 user=cassandra password=.... -schema "replication(strategy=SimpleStrategy,replication_factor=1)" keyspace="keyspace5" -col size=FIXED\(2048\) -errors ignore -rate threads=50  throttle=2000/s
```


after ~400K ops its visible that scylla has an issue

bad run using https://github.com/scylladb/scylla/commit/44e9e1041461ac513ab5f010786b35f0d89921a3 commit

```
Running WRITE with 50 threads for 100000000 iteration
Failed to connect over JMX; not collecting these stats
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
total,           282,     282,     282,     282,     0.3,     0.2,     0.3,     0.5,     1.1,     1.1,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
total,          2526,    2244,    2244,    2244,     4.4,     0.2,     3.6,   176.9,   198.8,   199.8,    2.0,  0.57775,      0,      0,       0,       0,       0,       0
total,          4526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     1.1,     1.1,    3.0,  0.35808,      0,      0,       0,       0,       0,       0
total,          6526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     1.1,    4.0,  0.25968,      0,      0,       0,       0,       0,       0
total,          8526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     1.0,     1.1,    5.0,  0.20375,      0,      0,       0,       0,       0,       0
total,         10526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,    6.0,  0.16767,      0,      0,       0,       0,       0,       0
total,         12526,    2000,    2000,    2000,     0.7,     0.2,     3.4,    10.3,    13.8,    14.3,    7.0,  0.14231,      0,      0,       0,       0,       0,       0
total,         14526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,    8.0,  0.12373,      0,      0,       0,       0,       0,       0
total,         16526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,    9.0,  0.10944,      0,      0,       0,       0,       0,       0
total,         18526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.6,     1.5,     5.0,   10.0,  0.09808,      0,      0,       0,       0,       0,       0
total,         20526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     1.0,     7.1,     9.6,   11.0,  0.08885,      0,      0,       0,       0,       0,       0
total,         22526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   12.0,  0.08123,      0,      0,       0,       0,       0,       0
total,         24526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   13.0,  0.07482,      0,      0,       0,       0,       0,       0
total,         26526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.2,   14.0,  0.06935,      0,      0,       0,       0,       0,       0
total,         28526,    2000,    2000,    2000,     0.6,     0.2,     1.9,    10.1,    14.7,    16.7,   15.0,  0.06459,      0,      0,       0,       0,       0,       0
total,         30526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   16.0,  0.06047,      0,      0,       0,       0,       0,       0
total,         32526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   17.0,  0.05684,      0,      0,       0,       0,       0,       0
total,         34526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     1.0,   18.0,  0.05363,      0,      0,       0,       0,       0,       0
total,         36526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     1.0,     1.3,   19.0,  0.05076,      0,      0,       0,       0,       0,       0
total,         38526,    2000,    2000,    2000,     0.4,     0.2,     0.4,     4.4,    11.0,    12.9,   20.0,  0.04817,      0,      0,       0,       0,       0,       0
total,         40526,    2000,    2000,    2000,     0.4,     0.2,     0.4,     8.4,    13.4,    13.8,   21.0,  0.04583,      0,      0,       0,       0,       0,       0
total,         42526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.2,   22.0,  0.04371,      0,      0,       0,       0,       0,       0
total,         44526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   23.0,  0.04179,      0,      0,       0,       0,       0,       0
total,         46526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.9,     4.4,     5.9,   24.0,  0.04002,      0,      0,       0,       0,       0,       0
total,         48526,    2000,    2000,    2000,     0.4,     0.2,     0.4,     5.7,     9.4,    12.9,   25.0,  0.03839,      0,      0,       0,       0,       0,       0
total,         50526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     1.0,     1.2,   26.0,  0.03690,      0,      0,       0,       0,       0,       0
total,         52525,    1999,    1999,    1999,     0.2,     0.2,     0.3,     0.4,     1.0,     1.3,   27.0,  0.03551,      0,      0,       0,       0,       0,       0
total,         54526,    2001,    2001,    2001,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   28.0,  0.03423,      0,      0,       0,       0,       0,       0
total,         56526,    2000,    2000,    2000,     0.4,     0.2,     0.4,     5.3,    11.3,    12.5,   29.0,  0.03303,      0,      0,       0,       0,       0,       0
total,         58526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     1.1,     7.9,     8.9,   30.0,  0.03192,      0,      0,       0,       0,       0,       0
total,         60526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     1.3,   31.0,  0.03088,      0,      0,       0,       0,       0,       0
total,         62526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     4.8,     8.6,     9.7,   32.0,  0.02990,      0,      0,       0,       0,       0,       0
total,         64526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   33.0,  0.02899,      0,      0,       0,       0,       0,       0
total,         66526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   34.0,  0.02813,      0,      0,       0,       0,       0,       0
total,         68526,    2000,    2000,    2000,     0.4,     0.2,     0.4,     7.9,    15.1,    17.2,   35.0,  0.02731,      0,      0,       0,       0,       0,       0
total,         70526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     1.0,     1.1,   36.0,  0.02655,      0,      0,       0,       0,       0,       0
total,         72526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     3.2,     9.7,    10.4,   37.0,  0.02582,      0,      0,       0,       0,       0,       0
total,         74526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     2.1,     8.7,     9.6,   38.0,  0.02514,      0,      0,       0,       0,       0,       0
total,         76526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   39.0,  0.02449,      0,      0,       0,       0,       0,       0
total,         78526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     1.0,     7.0,     9.8,   40.0,  0.02387,      0,      0,       0,       0,       0,       0
total,         80526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.6,     5.6,     6.6,   41.0,  0.02328,      0,      0,       0,       0,       0,       0
total,         82526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     1.1,     1.2,   42.0,  0.02272,      0,      0,       0,       0,       0,       0
total,         84526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   43.0,  0.02219,      0,      0,       0,       0,       0,       0
total,         86526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   44.0,  0.02169,      0,      0,       0,       0,       0,       0
total,         88526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   45.0,  0.02120,      0,      0,       0,       0,       0,       0
total,         90526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     1.1,   46.0,  0.02074,      0,      0,       0,       0,       0,       0
total,         92526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   47.0,  0.02029,      0,      0,       0,       0,       0,       0
total,         94526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   48.0,  0.01987,      0,      0,       0,       0,       0,       0
total,         96526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     0.5,     1.0,     1.0,   49.0,  0.01946,      0,      0,       0,       0,       0,       0
total,         98526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.1,     1.1,   50.0,  0.01907,      0,      0,       0,       0,       0,       0
total,        100526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   51.0,  0.01869,      0,      0,       0,       0,       0,       0
total,        102526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   52.0,  0.01833,      0,      0,       0,       0,       0,       0
total,        104526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.1,   53.0,  0.01799,      0,      0,       0,       0,       0,       0
total,        106526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     2.4,   54.0,  0.01765,      0,      0,       0,       0,       0,       0
total,        108526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     1.2,   55.0,  0.01733,      0,      0,       0,       0,       0,       0
total,        110526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.0,   56.0,  0.01702,      0,      0,       0,       0,       0,       0
total,        112526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     1.2,   57.0,  0.01672,      0,      0,       0,       0,       0,       0
total,        114526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.0,     2.6,   58.0,  0.01643,      0,      0,       0,       0,       0,       0
total,        116526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.5,     1.0,     1.0,   59.0,  0.01615,      0,      0,       0,       0,       0,       0
total,        118526,    2000,    2000,    2000,     0.5,     0.2,     0.4,    10.1,    24.4,    25.9,   60.0,  0.01588,      0,      0,       0,       0,       0,       0
total,        120526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     1.9,     2.2,   61.0,  0.01562,      0,      0,       0,       0,       0,       0
total,        122526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.7,     4.8,     5.7,   62.0,  0.01536,      0,      0,       0,       0,       0,       0
total,        124526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.6,     2.4,     3.7,   63.0,  0.01512,      0,      0,       0,       0,       0,       0
total,        126526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.8,     7.3,     9.2,   64.0,  0.01488,      0,      0,       0,       0,       0,       0
total,        128526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     1.5,     2.5,   65.0,  0.01465,      0,      0,       0,       0,       0,       0
total,        130526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.9,     5.9,     6.7,   66.0,  0.01443,      0,      0,       0,       0,       0,       0
total,        132526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     1.1,     2.0,   67.0,  0.01421,      0,      0,       0,       0,       0,       0
total,        134526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.8,     8.6,     9.6,   68.0,  0.01400,      0,      0,       0,       0,       0,       0
total,        136526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     1.3,     1.9,   69.0,  0.01380,      0,      0,       0,       0,       0,       0
total,        138526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.8,     4.9,     8.2,   70.0,  0.01360,      0,      0,       0,       0,       0,       0
total,        140526,    2000,    2000,    2000,     0.3,     0.3,     0.4,     0.8,     2.4,     5.3,   71.0,  0.01341,      0,      0,       0,       0,       0,       0
total,        142524,    1998,    1998,    1998,     0.4,     0.3,     0.4,     1.3,    11.3,    14.3,   72.0,  0.01322,      0,      0,       0,       0,       0,       0
total,        144525,    2001,    2001,    2001,     0.3,     0.3,     0.4,     0.8,     2.0,     2.5,   73.0,  0.01304,      0,      0,       0,       0,       0,       0
total,        146526,    2001,    2001,    2001,     0.5,     0.3,     0.5,     6.8,    11.7,    12.7,   74.0,  0.01286,      0,      0,       0,       0,       0,       0
total,        148085,    1559,    1559,    1559,     0.4,     0.3,     0.4,     3.1,    11.3,    12.8,   75.0,  0.01302,      0,      0,       0,       0,       0,       0
total,        148406,     321,     321,     321,   187.6,     3.0,  1200.6,  1212.2,  1214.3,  1214.3,   76.0,  0.02689,      0,      0,       0,       0,       0,       0
total,        152526,    4120,    4120,    4120,     4.0,     1.4,     4.6,   170.7,   172.6,   173.1,   77.0,  0.03265,      0,      0,       0,       0,       0,       0
total,        154409,    1883,    1883,    1883,     0.4,     0.3,     0.4,     1.5,    15.9,    16.5,   78.0,  0.03225,      0,      0,       0,       0,       0,       0
total,        156526,    2117,    2117,    2117,     9.7,     0.7,     7.6,   182.8,   194.6,   195.7,   79.0,  0.03198,      0,      0,       0,       0,       0,       0
total,        158526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.7,     2.1,   80.0,  0.03158,      0,      0,       0,       0,       0,       0
total,        160526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,   81.0,  0.03118,      0,      0,       0,       0,       0,       0
total,        162526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   82.0,  0.03080,      0,      0,       0,       0,       0,       0
total,        164526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,   83.0,  0.03043,      0,      0,       0,       0,       0,       0
total,        166526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   84.0,  0.03007,      0,      0,       0,       0,       0,       0
total,        168526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,   85.0,  0.02971,      0,      0,       0,       0,       0,       0
total,        170526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.0,   86.0,  0.02936,      0,      0,       0,       0,       0,       0
total,        172526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,   87.0,  0.02902,      0,      0,       0,       0,       0,       0
total,        174526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   88.0,  0.02869,      0,      0,       0,       0,       0,       0
total,        176526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.1,   89.0,  0.02837,      0,      0,       0,       0,       0,       0
total,        178526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.7,     1.1,   90.0,  0.02805,      0,      0,       0,       0,       0,       0
total,        180526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   91.0,  0.02774,      0,      0,       0,       0,       0,       0
total,        182526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.2,   92.0,  0.02744,      0,      0,       0,       0,       0,       0
total,        184526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,   93.0,  0.02714,      0,      0,       0,       0,       0,       0
total,        186526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   94.0,  0.02685,      0,      0,       0,       0,       0,       0
total,        188526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     1.1,   95.0,  0.02657,      0,      0,       0,       0,       0,       0
total,        190526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   96.0,  0.02629,      0,      0,       0,       0,       0,       0
total,        192526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,   97.0,  0.02602,      0,      0,       0,       0,       0,       0
total,        194526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.6,   98.0,  0.02575,      0,      0,       0,       0,       0,       0
total,        196526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,   99.0,  0.02549,      0,      0,       0,       0,       0,       0
total,        198526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     1.0,  100.0,  0.02524,      0,      0,       0,       0,       0,       0
total,        200526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.2,  101.0,  0.02499,      0,      0,       0,       0,       0,       0
total,        202526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  102.0,  0.02474,      0,      0,       0,       0,       0,       0
total,        204526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  103.0,  0.02450,      0,      0,       0,       0,       0,       0
total,        206526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.0,  104.0,  0.02426,      0,      0,       0,       0,       0,       0
total,        208526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  105.0,  0.02403,      0,      0,       0,       0,       0,       0
total,        210526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  106.0,  0.02380,      0,      0,       0,       0,       0,       0
total,        212526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.7,  107.0,  0.02358,      0,      0,       0,       0,       0,       0
total,        214526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     0.5,     0.6,     0.7,  108.0,  0.02336,      0,      0,       0,       0,       0,       0
total,        216526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     2.3,     8.3,     8.8,  109.0,  0.02314,      0,      0,       0,       0,       0,       0
total,        218526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     3.0,     5.5,  110.0,  0.02293,      0,      0,       0,       0,       0,       0
total,        220526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  111.0,  0.02273,      0,      0,       0,       0,       0,       0
total,        222526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.3,  112.0,  0.02252,      0,      0,       0,       0,       0,       0
total,        224526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  113.0,  0.02232,      0,      0,       0,       0,       0,       0
total,        226526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  114.0,  0.02213,      0,      0,       0,       0,       0,       0
total,        228526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  115.0,  0.02193,      0,      0,       0,       0,       0,       0
total,        230526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  116.0,  0.02174,      0,      0,       0,       0,       0,       0
total,        232526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     2.0,  117.0,  0.02156,      0,      0,       0,       0,       0,       0
total,        234526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  118.0,  0.02137,      0,      0,       0,       0,       0,       0
total,        236526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  119.0,  0.02119,      0,      0,       0,       0,       0,       0
total,        238526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     1.9,  120.0,  0.02102,      0,      0,       0,       0,       0,       0
total,        240526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  121.0,  0.02084,      0,      0,       0,       0,       0,       0
total,        242526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     2.0,  122.0,  0.02067,      0,      0,       0,       0,       0,       0
total,        244526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  123.0,  0.02050,      0,      0,       0,       0,       0,       0
total,        246526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  124.0,  0.02034,      0,      0,       0,       0,       0,       0
total,        248526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  125.0,  0.02017,      0,      0,       0,       0,       0,       0
total,        250526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.6,  126.0,  0.02001,      0,      0,       0,       0,       0,       0
total,        252526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  127.0,  0.01985,      0,      0,       0,       0,       0,       0
total,        254526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  128.0,  0.01970,      0,      0,       0,       0,       0,       0
total,        256526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.6,     0.6,  129.0,  0.01955,      0,      0,       0,       0,       0,       0
total,        258526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  130.0,  0.01940,      0,      0,       0,       0,       0,       0
total,        260526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     1.2,     2.8,  131.0,  0.01925,      0,      0,       0,       0,       0,       0
total,        262526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  132.0,  0.01910,      0,      0,       0,       0,       0,       0
total,        264526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  133.0,  0.01896,      0,      0,       0,       0,       0,       0
total,        266526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     6.4,     8.0,  134.0,  0.01881,      0,      0,       0,       0,       0,       0
total,        268526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.6,  135.0,  0.01867,      0,      0,       0,       0,       0,       0
total,        270526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  136.0,  0.01854,      0,      0,       0,       0,       0,       0
total,        272526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  137.0,  0.01840,      0,      0,       0,       0,       0,       0
total,        274526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  138.0,  0.01827,      0,      0,       0,       0,       0,       0
total,        276526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     5.4,  139.0,  0.01813,      0,      0,       0,       0,       0,       0
total,        278526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  140.0,  0.01800,      0,      0,       0,       0,       0,       0
total,        280526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.7,  141.0,  0.01788,      0,      0,       0,       0,       0,       0
total,        282526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.6,  142.0,  0.01775,      0,      0,       0,       0,       0,       0
total,        284526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     2.6,     4.6,  143.0,  0.01763,      0,      0,       0,       0,       0,       0
total,        286526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.4,     4.5,     6.0,  144.0,  0.01750,      0,      0,       0,       0,       0,       0
total,        288526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  145.0,  0.01738,      0,      0,       0,       0,       0,       0
total,        290526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     1.9,  146.0,  0.01726,      0,      0,       0,       0,       0,       0
total,        292526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  147.0,  0.01714,      0,      0,       0,       0,       0,       0
total,        294526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  148.0,  0.01703,      0,      0,       0,       0,       0,       0
total,        296526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  149.0,  0.01691,      0,      0,       0,       0,       0,       0
total,        298526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     1.8,  150.0,  0.01680,      0,      0,       0,       0,       0,       0
total,        300526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     2.6,     3.7,  151.0,  0.01669,      0,      0,       0,       0,       0,       0
total,        302526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  152.0,  0.01658,      0,      0,       0,       0,       0,       0
total,        304526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.4,  153.0,  0.01647,      0,      0,       0,       0,       0,       0
total,        306526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  154.0,  0.01636,      0,      0,       0,       0,       0,       0
total,        308526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.5,  155.0,  0.01626,      0,      0,       0,       0,       0,       0
total,        310526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  156.0,  0.01615,      0,      0,       0,       0,       0,       0
total,        312526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.6,  157.0,  0.01605,      0,      0,       0,       0,       0,       0
total,        314526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.5,     0.6,  158.0,  0.01595,      0,      0,       0,       0,       0,       0
total,        316526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  159.0,  0.01585,      0,      0,       0,       0,       0,       0
total,        318526,    2000,    2000,    2000,     0.3,     0.2,     0.3,     0.5,     4.6,     6.6,  160.0,  0.01575,      0,      0,       0,       0,       0,       0
total,        320526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  161.0,  0.01565,      0,      0,       0,       0,       0,       0
total,        322526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  162.0,  0.01555,      0,      0,       0,       0,       0,       0
total,        324526,    2000,    2000,    2000,     0.2,     0.2,     0.3,     0.4,     0.4,     0.5,  163.0,  0.01546,      0,      0,       0,       0,       0,       0
total,        326526,    2000,    2000,    2000,     0.3,     0.2,     0.4,     0.4,     0.6,     0.8,  164.0,  0.01536,      0,      0,       0,       0,       0,       0
total,        328526,    2000,    2000,    2000,     0.3,     0.3,     0.4,     0.5,     0.5,     2.0,  165.0,  0.01527,      0,      0,       0,       0,       0,       0
total,        330526,    2000,    2000,    2000,     0.3,     0.3,     0.4,     0.5,     0.5,     0.6,  166.0,  0.01518,      0,      0,       0,       0,       0,       0
total,        332526,    2000,    2000,    2000,     0.3,     0.3,     0.4,     0.5,     0.5,     0.5,  167.0,  0.01509,      0,      0,       0,       0,       0,       0
total,        334526,    2000,    2000,    2000,     0.3,     0.3,     0.4,     0.5,     0.5,     0.6,  168.0,  0.01500,      0,      0,       0,       0,       0,       0
total,        334859,     333,     333,     333,     0.3,     0.3,     0.4,     0.5,     0.5,     0.5,  169.0,  0.01578,      0,      0,       0,       0,       0,       0
total,        338526,    3667,    3667,    3667,    17.6,     1.4,     4.1,  1152.4,  1183.8,  1187.0,  170.0,  0.07011,      0,      0,       0,       0,       0,       0
total,        340526,    2000,    2000,    2000,     0.3,     0.3,     0.4,     0.5,     0.6,     1.9,  171.0,  0.06967,      0,      0,       0,       0,       0,       0
total,        340860,     334,     334,     334,     0.3,     0.3,     0.4,     0.5,     0.5,     0.5,  172.0,  0.06976,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during SIMPLE write query at consistency QUORUM (1 replica were required but only 0 acknowledged the write)
total,        341076,     216,     216,     216,   655.4,     2.8,  2835.3,  2845.8,  2845.8,  2845.8,  174.0,  0.07030,      0,      0,       0,       0,       0,       0
```

**Comment by slivne** [comment]
I ran the tests on the same server and between runs I cleared the scylla data and commitlog directory ``` # rm -Rf /var//lib/scylla/data/* /var/lib/scylla/commitlog/*```
so in every test I start scylla with a clean state and ran the workload.

**Comment by slivne** [comment]
@xemul will look at what the change may have done

**Comment by slivne** [comment]
@xemul ping

**Comment by xemul** [comment]
Decoding: with "newer" seastar the advertised write max buffer size is 128k, with "older" it's 84k. Everything else (on IO level) is the same.

**Comment by xemul** [comment]
![seastar-write-buffer-diff](https://user-images.githubusercontent.com/4498177/172854828-389fa997-2b3e-414e-9b0c-7d7b1ff10770.png)

compaction and flush classes manage to consume more IOPS using smaller buffer

**Comment by slivne** [comment]
I think commitlog writes 128K buffers.

what would happen if we send a 128K buffer and the limit is 84K would it be split into two writes ?

**Comment by avikivity** [comment]
My eyes are bleeding from the 3 minute queue delay

**Comment by avikivity** [comment]
So, the scheduler thought it was commitlog was consuming less disk than it actually was, and so gave too much to commitlog? Are we in fact disk bound in this workload?

**Comment by xemul** [comment]
Checked scylladb/seastar@bef574d551c3d817da385b5b5112c4d193b60c9f which only has these 4 above it:
```
3b4e42d7    condition-variable: Fix broadcast to handle "when(pred)" usage
1b3403a7    condition-variable: Adjust when(pred) evaulation to match wait(pred) + tests
5773f962    coroutine: parallel_for_each: set_callback: destroy future after move
b5eced32    Merge "Calculate max IO lengths as lengths" from Pavel E
```
still broken. So 99.9% the fixing commit is scylladb/seastar@b5eced32ded7c970a4ebdd2e4162ad757de1a887

**Comment by avikivity** [comment]
@xemul so let's backport it.

**Comment by xemul** [comment]
> btw, what we probably should do if a request can't be accounted, is split it into smaller requests and merge it back before responding to the caller

So far it's only the commitlog that misbehaves like that. All the others sit on top of iostreams that obey maximum buffer size. If it's OK to split commitlog request behind the scenes, why doesn't it do it itself?

**Comment by xemul** [comment]
> @xemul so let's backport it.

@avikivity , but that's not the "real" fix, it just happens that this patch(set) calculates the limits more carefully so that the max-write-buffer becomes larger than the hard-coded commitlog buffer size

**Comment by avikivity** [comment]
I forgot we had a max-write-buffer API, what is it?

**Comment by xemul** [comment]
Almost. The disk_write_max_length() one

**Comment by avikivity** [comment]
Commitlog could split it, but if we force every non-iostream user to do it, it's more work for everyone.

The way I see it, if you can easily respect disk_write_max_length() you will spend less memory and get better latency for individual request (though, if you're reading a stream, you're probably interested in last-byte latency, not first-byte latency).

If you don't respect disk_write_max_length() can seastar splits it behind your back, then you don't get these benefits, but at least you don't impact other fibers. Wait - you only impact yourself if you don't respect it.

So yes we should do it in commitlog.

**Comment by avikivity** [comment]
So let's backport it, and also fix commitlog.

**Comment by xemul** [comment]
| ... and also fix commitlog.
#10769

**Comment by xemul** [comment]
527a75a4c0cf238f6cd1cd7e3c8d5d25ba183c34 in branch-5.0 (@slivne)

**Comment by slivne** [comment]
Great - will be part of 5.0.rc8

**Comment by tzach** [comment]
@xemul Is this issue fixed in rc8?

**Comment by xemul** [comment]
@tzach , yes

```
commit f28542a71ec5c798766dea4b9492a5e3cf49439e (HEAD -> br-5.0-rc8, tag: scylla-5.0.rc8, origin/next-5.0, origin/branch-5.0)
Author: Yaron Kaikov <yaronkaikov@scylladb.com>
Date:   Sun Jun 12 14:44:47 2022 +0300

    release: prepare for 5.0.rc8

commit 527a75a4c0cf238f6cd1cd7e3c8d5d25ba183c34
Author: Pavel Emelyanov <xemul@scylladb.com>
Date:   Thu Jun 9 21:15:21 2022 +0300

    Update seastar submodule (Calculate max IO lengths as lengths)
    
    * seastar 8b2c13b3...dbf79189 (1):
      > Merge 'Calculate max IO lengths as lengths'
         io_queue: Type alias for internal::io_direction_and_length
         io_queue, fair_group: Throw instead of assert
         io_queue: Keep max lengths on board
         io_queue: Toss request_fq_ticket()
         io_queue: Introduce make_ticket() helper
         io_queue: Remove max_ticket_size
         io_queue: Make make_ticket() non-brancy
         io_queue: Add devid to group creation log
    
    tests: cstress(release)
    fixes: #10704


```

**Comment by pragmaxim** [comment]
Guys it improved to make it through the cassandra stress test but imho the backpressure still does not work, so heavy data loading works fine if scylla has unlimited memory access but when the allocations reach the limits then backpressure does not kick in and scylla crashes.

**Comment by avikivity** [comment]
@pragmaxim please open a separate issue and provide much more information (especially monitoring snapshots). We can't fix bug if the only information is "backpressure is still broken".

**Comment by pragmaxim** [comment]
@avikivity I've spent too much time on this, I have to move on and index the data in 2-3 runs.
![Screenshot from 2022-08-24 11-24-59](https://user-images.githubusercontent.com/8983344/186382851-87f97d5b-07f9-438b-a53e-28b625f55a2c.png)

**Comment by roydahan** [comment]
5.1 release is just RC0.
Please try with 5.0 or wait for later RC of 5.1

**Comment by pragmaxim** [comment]
@roydahan I think `5.1` is the best out there https://hub.docker.com/r/scylladb/scylla/tags with this fix merged ... @avikivity issue created https://github.com/scylladb/scylladb/issues/11368 ... please let me know what else I can provide. This seems to be quite serious, indexing with single thread being able to crash scylla :shrug:

**Comment by pragmaxim** [comment]
Yeah but there is no `5.0` docker container which could be used to reproduce this.

**Comment by roydahan** [comment]
docker pull scylladb/scylla:5.0.1
