### ISSUE TITLE
scylla falls into background when loaded on Ubuntu 16.04

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1199]
## Installation details

Scylla version (or git commit hash): 2e08d0f698090f978f5a94e3ae4fc73f0d8c6b5b
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 15.10
## Hardware details (for performance issues)

Platform (physical/VM/cloud instance type/docker): physical

Running a scylla with a following command it's being "stopped" as if Ctl-Z was pressed:

```
scylla  --developer-mode 1 --datadir tmp --commitlog-directory tmp_commitlog
...
INFO  2016-04-17 22:54:32,809 [shard 1] database - Keyspace tmp/keyspace1: Reading CF standard1
INFO  2016-04-17 22:54:32,809 [shard 3] database - Populating Keyspace keyspace1
INFO  2016-04-17 22:54:32,810 [shard 3] database - Keyspace tmp/keyspace1: Reading CF standard1
INFO  2016-04-17 22:54:32,810 [shard 2] database - Populating Keyspace keyspace1
INFO  2016-04-17 22:54:32,810 [shard 2] database - Keyspace tmp/keyspace1: Reading CF standard1

[1]+  Stopped                 build/release/scylla --developer-mode 1 --datadir tmp --commitlog-directory tmp_commit
```

After invoking `fg` scylla continues as expected.

**Comment by vladzcloudius** [comment]
The root cause of this behavior is in `supervisor_notify()` code:
```
void
supervisor_notify(sstring msg, bool ready = false) {
    static const char *is_upstart = getenv("UPSTART_JOB");

    startlog.trace("{}", msg);
#ifdef HAVE_LIBSYSTEMD
    auto ready_msg = ready ? "READY=1\n" : "";
    sd_notify(0, sprint("%sSTATUS=%s\n", ready_msg, msg).c_str());
#endif
    if (is_upstart != nullptr && ready) {
        raise(SIGSTOP);
    }
}
```

and in the fact that `UPSTART_JOB` is defined:
```
# echo $UPSTART_JOB 
unity7
```

Therefore when `supervisor_notify()` is invokes with `ready=True` it would cause scylla to raise `SIGSTOP`.

**Comment by vladzcloudius** [comment]
The relevant code was added in a patch 4162fb158 in order to fix issue #846. This obviously doesn't work as expected.
@syuu1228 , @nyh, could u, pls., reconsider a fix for #846 to something that would work on other Ubuntu setups too.

**Comment by tzach** [comment]
We will provide support for Ubuntu 15.10 not 15.04
https://github.com/scylladb/scylla/issues/609

**Comment by vladzcloudius** [comment]
On 04/18/2016 01:52 PM, Tzach Livyatan wrote:
>
> We will provide support for Ubuntu 15.10 not 15.04
> #609 <https://github.com/scylladb/scylla/issues/609>
>

I have 15.10 -  my bad. I'll update the issue.

**Comment by vladzcloudius** [comment]
@tzach Could u reopen it, pls. It was just a typo.

**Comment by syuu1228** [comment]
This was fixed on "[PATCH scylla v3 4/6] dist/ubuntu: add dependency for libsystemd-dev to handle startup correctly on recent versions of Ubuntu", part of Ubuntu 16.04 patchset.

**Comment by syuu1228** [comment]
The fix merged, can close this.
https://github.com/scylladb/scylla/commit/fa0b90b727d255114063a443f1cc175ed5619b24

**Comment by vladzcloudius** [comment]
The issue is still reproducible with the master HEAD 02530faeb22d885127a9e2311dc9b9a83384cb61
All mentioned above code that caused (and still causes) the original issue is still where it was.

@syuu1228 Could u clarify, please, how the patches above were supposed to fix the issue?
