### ISSUE TITLE
If sstable write fails a file object is destroyed befor IO is complete.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2122]
*Installation details*
Scylla version (or git commit hash): 274bcd415a0e71ed1d79148df4a6d395636c8f29

**Comment by gleb-cloudius** [comment]
Fixed by 0977f4fdf8f1334d4544015c65a14f3977979f91

**Comment by avikivity** [comment]
I think this is scylladb/scylla#2122 (not fixed on 1.6 or enterprise!). @gleb-cloudius opinion please.

**Comment by tzach** [comment]
@avikivity @gleb-cloudius this fix was backported to 1.5 and 1.7, why not 1.6?
