### ISSUE TITLE
estimated_histogram is not efficient 

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2785]
*Installation details*
Scylla version (or git commit hash): d0d8bdf61565a89c84f621fed8fd9a060853acfe

estimated_histogram is used very often during each query, but it does a binary search to find a bucket 
when values are added. It can use similar logic to log_histogram where finding a bucket is a matter of simple calculation.

**Comment by amnonh** [comment]
well, it's a binary search of a logarithmic distributed buckets, so
we do talk about log(log(n)) while it could be improved with a log calculation it will not have  a huge performance improvement

**Comment by gleb-cloudius** [comment]
On Sun, Sep 17, 2017 at 06:43:48AM +0000, Amnon Heiman wrote:
> well, it's a binary search of a logarithmic distributed buckets, so
> we do talk about log(log(n)) while it could be improved with a log calculation it will not have  a huge performance improvement
> 
Why is it a binary search? It should be a simple calculation to get to a
correct bucket.

--
			Gleb.

**Comment by amnonh** [comment]
On Sun, Sep 17, 2017 at 9:50 AM, Gleb Natapov <notifications@github.com>
wrote:

> On Sun, Sep 17, 2017 at 06:43:48AM +0000, Amnon Heiman wrote:
> > well, it's a binary search of a logarithmic distributed buckets, so
> > we do talk about log(log(n)) while it could be improved with a log
> calculation it will not have a huge performance improvement
> >
> Why is it a binary search? It should be a simple calculation to get to a
> correct bucket.
>
It's not a 2^ buckets, so it's either doing trunc(log(n/min_bucket, 0.2))
or a binary search, not sure what is faster

**Comment by gleb-cloudius** [comment]
On Sun, Sep 17, 2017 at 06:53:08AM +0000, Amnon Heiman wrote:
> On Sun, Sep 17, 2017 at 9:50 AM, Gleb Natapov <notifications@github.com>
> wrote:
> 
> > On Sun, Sep 17, 2017 at 06:43:48AM +0000, Amnon Heiman wrote:
> > > well, it's a binary search of a logarithmic distributed buckets, so
> > > we do talk about log(log(n)) while it could be improved with a log
> > calculation it will not have a huge performance improvement
> > >
> > Why is it a binary search? It should be a simple calculation to get to a
> > correct bucket.
> >
> It's not a 2^ buckets, so it's either doing trunc(log(n/min_bucket, 0.2))
> or a binary search, not sure what is faster
> 
Lets make it 2^ buckets, although I do not see why trunc() will be slow.

--
			Gleb.

**Comment by amnonh** [comment]
On Sun, Sep 17, 2017 at 9:55 AM, Gleb Natapov <notifications@github.com>
wrote:

> On Sun, Sep 17, 2017 at 06:53:08AM +0000, Amnon Heiman wrote:
> > On Sun, Sep 17, 2017 at 9:50 AM, Gleb Natapov <notifications@github.com>
> > wrote:
> >
> > > On Sun, Sep 17, 2017 at 06:43:48AM +0000, Amnon Heiman wrote:
> > > > well, it's a binary search of a logarithmic distributed buckets, so
> > > > we do talk about log(log(n)) while it could be improved with a log
> > > calculation it will not have a huge performance improvement
> > > >
> > > Why is it a binary search? It should be a simple calculation to get to
> a
> > > correct bucket.
> > >
> > It's not a 2^ buckets, so it's either doing trunc(log(n/min_bucket, 0.2))
> > or a binary search, not sure what is faster
> >
> Lets make it 2^ buckets, although I do not see why trunc() will be slow.
>
But I need 1.2 buckets, and it's not just the trunc, or the log calculation
those are multiple
things that need to be done.

I can switch to direct calculation (I doubt that it's going to have any
effect) I can optimize with binary tree on top of the buckets
To save the index calculation
and can do some optimization about the first bucket to start the search from

**Comment by gleb-cloudius** [comment]
On Sun, Sep 17, 2017 at 12:00:26AM -0700, Amnon Heiman wrote:
> On Sun, Sep 17, 2017 at 9:55 AM, Gleb Natapov <notifications@github.com>
> wrote:
> 
> > On Sun, Sep 17, 2017 at 06:53:08AM +0000, Amnon Heiman wrote:
> > > On Sun, Sep 17, 2017 at 9:50 AM, Gleb Natapov <notifications@github.com>
> > > wrote:
> > >
> > > > On Sun, Sep 17, 2017 at 06:43:48AM +0000, Amnon Heiman wrote:
> > > > > well, it's a binary search of a logarithmic distributed buckets, so
> > > > > we do talk about log(log(n)) while it could be improved with a log
> > > > calculation it will not have a huge performance improvement
> > > > >
> > > > Why is it a binary search? It should be a simple calculation to get to
> > a
> > > > correct bucket.
> > > >
> > > It's not a 2^ buckets, so it's either doing trunc(log(n/min_bucket, 0.2))
> > > or a binary search, not sure what is faster
> > >
> > Lets make it 2^ buckets, although I do not see why trunc() will be slow.
> >
> But I need 1.2 buckets, and it's not just the trunc, or the log calculation
> those are multiple
> things that need to be done.
> 
Why do you _need_ 1.2 buckets? Isn't it just an arbitrary chosen value?

--
			Gleb.

**Comment by avikivity** [comment]
Look at `log_histogram`, it computes the index with just a few instructions for sub-power-of-two buckets.

**Comment by amnonh** [comment]
it's not too bad to do a log-based calculation, but the buckets exponential is 1.2.
We try to be similar to Cassandra in the accuracy.

Neither log calculation, nor binary search in a tree/array of 92 buckets is too bad.

**Comment by avikivity** [comment]
We can do 1.125 or 1.25 with logarithmic histograms.

**Comment by amnonh** [comment]
I suggest replacing the implementation to log_heap and rename the issue accordingly

**Comment by amnonh** [comment]
Fixed by d17b05e9112b615bdc055e12c740906aaae070d9

**Comment by avikivity** [comment]
Not really fixed, we added a new type, but the old type remains.
