### ISSUE TITLE
Failure during resharding from 7 to 2 CPUs: runtime_error, SSTable write failed due to existence of TOC file

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3273]
I ran test that performed resharding from 7 to 2 CPUs) during stress I/O.
Cluster size: 1 node
The test ran on my laptop with 8 CPUs.
Test failed. Error I found in the system log:

INFO  2018-03-11 11:35:20,231 [shard 0] compaction - Resharding [/home/juliay/.dtest/dtest-06LKq4/test/node1/data/keyspace1/standard1-fa9484c0250d11e88717000000000003/keyspace1-standard1-ka-178-Data.db:level=0, ]
INFO  2018-03-11 11:35:20,232 [shard 0] storage_service - load_peer_features: peer_features size=0
INFO  2018-03-11 11:35:20,232 [shard 0] storage_service - Checking remote features skipped, since this node is a new seed node which knows nothing about the cluster
INFO  2018-03-11 11:35:20,232 [shard 0] storage_service - Starting up server gossip
**ERROR 2018-03-11 11:35:20,233 [shard 0] compaction_manager - resharding failed: std::runtime_error (SSTable write failed due to existence of TOC file for generation 216 of keyspace1.standard1)
INFO  2018-03-11 11:35:20,233 [shard 0] compaction - Resharding [/home/juliay/.dtest/dtest-06LKq4/test/node1/data/keyspace1/standard1-fa9484c0250d11e88717000000000003/keyspace1-standard1-ka-206-Data.db:level=0, ]**

Log:
[system7_2.log](https://github.com/scylladb/scylla/files/1800205/system7_2.log)

**Comment by slivne** [comment]
@juliayakovlev can you please specify which version / commit

(we need to know if this is an issue in released versions)

**Comment by juliayakovlev** [comment]
@slivne 
Last commit: 101e909483fa03ca9c4a7841d3d6a1c8f393f61d

**Comment by juliayakovlev** [comment]
More details I found in the log file:
INFO  2018-03-19 12:04:33,567 [shard 0] compaction - Compacted 4 sstables to [/home/juliay/.dtest/dtest-iiAj1s/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-77-Data.db:level=0, ]. 34488 bytes to 187
32 (~54% of original) in 44ms = 0.41MB/s. ~512 total partitions merged to 1.
ERROR 2018-03-19 12:04:33,569 [shard 4] database - Failed to flush memtable, system:compaction_history
WARN  2018-03-19 12:04:33,569 [shard 4] seastar - Exceptional future ignored: std::runtime_error (SSTable write failed due to existence of TOC file for generation 11 of system.compaction_history), backtrace:   0x58a5c8
  0xc4073a
  0x588ef6
  0x5890b9
  0x64bd14
  0x66d8eb
  0x71472d
  /lib64/libpthread.so.0+0x761a
  /lib64/libc.so.6+0x11798e
====================================
INFO  2018-03-19 12:04:34,631 [shard 0] compaction - Resharded 1 sstables to [/home/juliay/.dtest/dtest-iiAj1s/test/node1/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/system_schema-keyspaces-ka-45-Data.db:level=0, ]. 56624 bytes to 1633004 (~2883% of original) in 178ms = 8.75MB/s. ~128 total partitions merged to 2.
Aborting on shard 4.
Backtrace:
  0x00000000005a60ec
  0x00000000005a6395
  0x00000000005a6443
  /lib64/libpthread.so.0+0x0000000000012aef
  /lib64/libc.so.6+0x000000000003766a
  /lib64/libc.so.6+0x0000000000039380
  0x0000000000eaf134
  0x0000000000d02e52
  0x0000000000d051cb
  0x0000000000c28b43
  0x0000000000d166ab
  0x0000000000d187e3
  0x0000000000d19cbb
  0x0000000000588ef6
  0x00000000005890b9
  0x000000000064bd14
  0x000000000066d8eb
  0x000000000071472d
  /lib64/libpthread.so.0+0x000000000000761a
  /lib64/libc.so.6+0x000000000011798e

Log file:
[system_backtrace.log](https://github.com/scylladb/scylla/files/1824728/system_backtrace.log)

**Comment by raphaelsc** [comment]
On Mon, Mar 19, 2018 at 8:20 AM, juliayakovlev <notifications@github.com>
wrote:

> More details I found in the log file:
> INFO 2018-03-19 12:04:33,567 [shard 0] compaction - Compacted 4 sstables
> to [/home/juliay/.dtest/dtest-iiAj1s/test/node1/data/system/local-
> 7ad54392bcdd35a684174e047860b377/system-local-ka-77-Data.db:level=0, ].
> 34488 bytes to 187
> 32 (~54% of original) in 44ms = 0.41MB/s. ~512 total partitions merged to
> 1.
> ERROR 2018-03-19 12:04:33,569 [shard 4] database - Failed to flush
> memtable, system:compaction_history
> WARN 2018-03-19 12:04:33,569 [shard 4] seastar - Exceptional future
> ignored: std::runtime_error (SSTable write failed due to existence of TOC
> file for generation 11 of system.compaction_history), backtrace: 0x58a5c8
> 0xc4073a
> 0x588ef6
> 0x5890b9
> 0x64bd14
> 0x66d8eb
> 0x71472d
> /lib64/libpthread.so.0+0x761a
> /lib64/libc.so.6+0x11798e
>
> INFO 2018-03-19 12:04:34,631 [shard 0] compaction - Resharded 1 sstables
> to [/home/juliay/.dtest/dtest-iiAj1s/test/node1/data/system_
> schema/keyspaces-abac5682dea631c5b535b3d6cffd0f
> b6/system_schema-keyspaces-ka-45-Data.db:level=0, ]. 56624 bytes to
> 1633004 (~2883% of original) in 178ms = 8.75MB/s. ~128 total partitions
> merged to 2.
> Aborting on shard 4.
> Backtrace:
> 0x00000000005a60ec
> 0x00000000005a6395
> 0x00000000005a6443
> /lib64/libpthread.so.0+0x0000000000012aef
> /lib64/libc.so.6+0x000000000003766a
> /lib64/libc.so.6+0x0000000000039380
> 0x0000000000eaf134
> 0x0000000000d02e52
> 0x0000000000d051cb
> 0x0000000000c28b43
> 0x0000000000d166ab
> 0x0000000000d187e3
> 0x0000000000d19cbb
> 0x0000000000588ef6
> 0x00000000005890b9
> 0x000000000064bd14
> 0x000000000066d8eb
> 0x000000000071472d
> /lib64/libpthread.so.0+0x000000000000761a
> /lib64/libc.so.6+0x000000000011798e
>

This should be fixed in master, please rebase and retry

**Comment by juliayakovlev** [comment]
@raphaelsc 
I rebuilt Scylla, but still receive the problem:
INFO  2018-03-20 08:43:35,685 [shard 0] compaction - Resharding [/home/juliay/.dtest/dtest-DhzWft/test/node1/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/la-6-big-Data.db:level=0, ]
ERROR 2018-03-20 08:43:35,685 [shard 0] compaction_manager - resharding failed: std::runtime_error (SSTable write failed due to existence of TOC file for generation 11 of system.compaction_history)

**Comment by raphaelsc** [comment]
On Tue, Mar 20, 2018 at 4:11 AM, juliayakovlev <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc>
> I rebuilt Scylla, but still receive the problem:
> INFO 2018-03-20 08:43:35,685 [shard 0] compaction - Resharding
> [/home/juliay/.dtest/dtest-DhzWft/test/node1/data/system/
> compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/la-6-big-Data.db:level=0,
> ]
> ERROR 2018-03-20 08:43:35,685 [shard 0] compaction_manager - resharding
> failed: std::runtime_error (SSTable write failed due to existence of TOC
> file for generation 11 of system.compaction_history)
>

did you update the submodule? the fix was in seastar. please make sure
seastar has the commit bcfbe0c3f7f62af97d58bef4383d46864b32fbe7

**Comment by juliayakovlev** [comment]
Yes, I did whole procedure under scylla:
git pull
 git submodule update --init --recursive
sudo ./install-dependencies.sh
./configure.py --mode=release
ninja-build -j8

 And I can find this commit under scylla/seastar:
[juliay@juliay scylla]$ cd seastar/
[juliay@juliay seastar]$ git log | grep bcfbe0c3f7f62af97d58bef4383d46864b32fbe7
commit bcfbe0c3f7f62af97d58bef4383d46864b32fbe7

Do I have to perform something else?

**Comment by duarten** [comment]
I'm also hitting this issue. It happens when I stop a ccm cluster abrupt, and restart the nodes with resharding. In this particular, it happens when resharding goes from 8 to 15 CPUs. It doesn't always happen, so it's dependent on where the nodes are stopped.

```python
@staticmethod
def set_memory_param(smp):
    return '{}M'.format(512 * int(smp))

smp_before = 8
smp_after = 15
session = self.prepare(options={'hinted_handoff_enabled': False, 'shadow_round_ms': 1000, 'prometheus_port': 0}, jvm_args=['--smp', smp_before, '--memory', self.set_memory_param(smp_before)])

# start writing data

self.cluster.stop(gently=False)

for node in self.cluster.nodelist():
    node.start(jvm_args=['--smp', smp_after, '--memory', self.set_memory_param(smp_after)], wait_for_binary_proto=True)
```

In the logs I see:

```
ERROR 2018-03-22 12:41:03,362 [shard 0] database - Failed to flush memtable, ks:t, std::runtime_error (SSTable write failed due to existence of TOC file for generation 15 of ks.t)
Segmentation fault on shard 0.
```

With the following (not very helpful) backtrace:

```
operator()<seastar::future_state<> > at /home/duarten/code/scylla-dev/./seastar/core/future.hh:984
 (inlined by) run_and_dispose at /home/duarten/code/scylla-dev/./seastar/core/future.hh:413
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/duarten/code/scylla-dev/seastar/core/reactor.cc:2500
seastar::reactor::run_some_tasks() at /home/duarten/code/scylla-dev/seastar/core/reactor.cc:2910
seastar::reactor::run_some_tasks() at /usr/include/c++/7/chrono:377
 (inlined by) seastar::reactor::run() at /home/duarten/code/scylla-dev/seastar/core/reactor.cc:3057
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /home/duarten/code/scylla-dev/seastar/core/app-template.cc:180
main at /home/duarten/code/scylla-dev/main.cc:749
```

**Comment by duarten** [comment]
I wonder if this is related to commitlog replaying.
