### ISSUE TITLE
system_error (error system:32, Broken pipe) from other nodes while node stop

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#3461]
*Installation details*
Scylla version (or git commit hash): 2.2.rc1-0.20180516.eb646c61e
Cluster size: 1 TB 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-59a73726

while node a stops other nodes in the cluster are repporting system_error (error system:32, Broken pipe) with a backtrce:
```
2018-05-24 10:59:23,710 remote           L0097 INFO | [172.30.0.254] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpotZMGW -o BatchMode=yes -o ConnectTimeout=300 -o Serv
erAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-tls-1tb-7d-2-2-sct-7102347b.pem 172.30.0.254 "sudo systemctl restart scylla-server.service"'
2018-05-24 10:59:24,361 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 info   | Stopping Scylla JMX...
2018-05-24 10:59:24,713 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 notice | scylla-jmx.service: main process exited, code=exited, status=143/n/a
2018-05-24 10:59:24,730 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 notice | Unit scylla-jmx.service entered failed state.
2018-05-24 10:59:24,741 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 warning| scylla-jmx.service failed.
2018-05-24 10:59:24,747 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 info   | Stopping Scylla Server...
2018-05-24 10:59:24,795 asyncorereactor  L0383 DEBUG| Message pushed from server: <EventMessage(event_type=u'STATUS_CHANGE', trace_id=None, event_args={'change_type': u'DOWN', 'address': ('172.30.0.254', 9042)},
 stream_id=-1)>
2018-05-24 10:59:24,796 remote           L0197 DEBUG| [172.30.0.103] [stdout] May 24 10:59:24 info   |  [shard 0] gossip - InetAddress 172.30.0.254 is now DOWN, status = shutdown
2018-05-24 10:59:24,797 thread           L0062 WARNI| Host 172.30.0.254 has been marked down
2018-05-24 10:59:24,799 remote           L0197 DEBUG| [172.30.0.250] [stdout] May 24 10:59:24 info   |  [shard 0] gossip - InetAddress 172.30.0.254 is now DOWN, status = shutdown
2018-05-24 10:59:24,799 remote           L0197 DEBUG| [172.30.0.103] [stdout] May 24 10:59:24 warning|  [shard 0] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace
:   0x594718
2018-05-24 10:59:24,800 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x95d913
2018-05-24 10:59:24,800 remote           L0197 DEBUG| [172.30.0.216] [stdout] May 24 10:59:24 info   |  [shard 0] gossip - InetAddress 172.30.0.254 is now DOWN, status = shutdown
2018-05-24 10:59:24,800 remote           L0197 DEBUG| [172.30.0.250] [stdout] May 24 10:59:24 warning|  [shard 5] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace
:   0x594718
2018-05-24 10:59:24,801 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x2c9d970
2018-05-24 10:59:24,802 remote           L0197 DEBUG| [172.30.0.216] [stdout] May 24 10:59:24 warning|  [shard 7] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace
:   0x594718
2018-05-24 10:59:24,802 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x95d913
2018-05-24 10:59:24,804 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x2c9e949
2018-05-24 10:59:24,804 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x95d913
2018-05-24 10:59:24,804 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x2c9d970
2018-05-24 10:59:24,805 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x593026
2018-05-24 10:59:24,805 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x2c9d970
2018-05-24 10:59:24,806 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x2c9e949
2018-05-24 10:59:24,807 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x5931e1
2018-05-24 10:59:24,807 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x2c9e949
2018-05-24 10:59:24,808 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x593026
2018-05-24 10:59:24,808 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x593026
2018-05-24 10:59:24,809 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x5931e1
2018-05-24 10:59:24,808 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x658de7
2018-05-24 10:59:24,810 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x658de7
2018-05-24 10:59:23,710 remote           L0097 INFO | [172.30.0.254] Running '/bin/ssh  -a -x   -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpotZMGW -o BatchMode=yes -o ConnectTimeout=300 -o Serv
erAliveInterval=300 -l centos -p 22 -i /var/tmp/longevity-tls-1tb-7d-2-2-sct-7102347b.pem 172.30.0.254 "sudo systemctl restart scylla-server.service"'
2018-05-24 10:59:24,361 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 info   | Stopping Scylla JMX...
2018-05-24 10:59:24,713 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 notice | scylla-jmx.service: main process exited, code=exited, status=143/n/a
2018-05-24 10:59:24,730 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 notice | Unit scylla-jmx.service entered failed state.
2018-05-24 10:59:24,741 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 warning| scylla-jmx.service failed.
2018-05-24 10:59:24,747 remote           L0197 DEBUG| [172.30.0.254] [stdout] May 24 10:59:24 info   | Stopping Scylla Server...
2018-05-24 10:59:24,795 asyncorereactor  L0383 DEBUG| Message pushed from server: <EventMessage(event_type=u'STATUS_CHANGE', trace_id=None, event_args={'change_type': u'DOWN', 'address': ('172.30.0.254', 9042)},
 stream_id=-1)>
2018-05-24 10:59:24,796 remote           L0197 DEBUG| [172.30.0.103] [stdout] May 24 10:59:24 info   |  [shard 0] gossip - InetAddress 172.30.0.254 is now DOWN, status = shutdown
2018-05-24 10:59:24,797 thread           L0062 WARNI| Host 172.30.0.254 has been marked down
2018-05-24 10:59:24,799 remote           L0197 DEBUG| [172.30.0.250] [stdout] May 24 10:59:24 info   |  [shard 0] gossip - InetAddress 172.30.0.254 is now DOWN, status = shutdown
2018-05-24 10:59:24,799 remote           L0197 DEBUG| [172.30.0.103] [stdout] May 24 10:59:24 warning|  [shard 0] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace
:   0x594718
2018-05-24 10:59:24,800 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x95d913
2018-05-24 10:59:24,800 remote           L0197 DEBUG| [172.30.0.216] [stdout] May 24 10:59:24 info   |  [shard 0] gossip - InetAddress 172.30.0.254 is now DOWN, status = shutdown
2018-05-24 10:59:24,800 remote           L0197 DEBUG| [172.30.0.250] [stdout] May 24 10:59:24 warning|  [shard 5] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace
:   0x594718
2018-05-24 10:59:24,801 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x2c9d970
2018-05-24 10:59:24,802 remote           L0197 DEBUG| [172.30.0.216] [stdout] May 24 10:59:24 warning|  [shard 7] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace
:   0x594718
2018-05-24 10:59:24,802 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x95d913
2018-05-24 10:59:24,804 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x2c9e949
2018-05-24 10:59:24,804 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x95d913
2018-05-24 10:59:24,804 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x2c9d970
2018-05-24 10:59:24,805 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x593026
2018-05-24 10:59:24,805 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x2c9d970
2018-05-24 10:59:24,806 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x2c9e949
2018-05-24 10:59:24,807 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x5931e1
2018-05-24 10:59:24,807 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x2c9e949
2018-05-24 10:59:24,808 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x593026
2018-05-24 10:59:24,808 remote           L0197 DEBUG| [172.30.0.250] [stdout]   0x593026
2018-05-24 10:59:24,809 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x5931e1
2018-05-24 10:59:24,808 remote           L0197 DEBUG| [172.30.0.103] [stdout]   0x658de7
2018-05-24 10:59:24,810 remote           L0197 DEBUG| [172.30.0.216] [stdout]   0x658de7
```
decoded:
```
[centos@ip-172-30-0-103 ~]$ addr2line -Cpife /usr/lib/debug/.build-id/55/77803f60551b18ecf4bf79b7df0e4e9e4114dd.debug 

?? ??:0
0x594718
0x95d913
0x2c9d970
0x2c9e949
0x593026
0x5931e1
0x658de7
0x65f6d3
0x72ec2d
/lib64/libpthread.so.0+0x7e24
/lib64/libc.so.6+0xfebac

seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /usr/src/debug/scylla-2.2.rc1/seastar/core/reactor.cc:4227
seastar::future<>::~future() at /usr/src/debug/scylla-2.2.rc1/seastar/core/future.hh:828
 (inlined by) seastar::tls::session::close() at /usr/src/debug/scylla-2.2.rc1/seastar/net/tls.cc:967
seastar::rpc::protocol<netw::serializer, netw::messaging_verb>::connection::stop_send_loop() at /usr/src/debug/scylla-2.2.rc1/seastar/rpc/rpc.hh:226
 (inlined by) seastar::rpc::protocol<netw::serializer, netw::messaging_verb>::client::client(seastar::rpc::protocol<netw::serializer, netw::messaging_verb>&, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::{lambda(seastar::future<>)#2}::operator()(seastar::future<>) const at /usr/src/debug/scylla-2.2.rc1/seastar/rpc/rpc_impl.hh:1109
 (inlined by) std::enable_if<!seastar::is_future<std::result_of<seastar::rpc::protocol<netw::serializer, netw::messaging_verb>::client::client(seastar::rpc::protocol<netw::serializer, netw::messaging_verb>&, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::{lambda(seastar::future<>)#2} (seastar::future<>&&)>::type>::value, seastar::future<> >::type seastar::do_void_futurize_apply<seastar::rpc::protocol<netw::serializer, netw::messaging_verb>::client::client(seastar::rpc::protocol<netw::serializer, netw::messaging_verb>&, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::{lambda(seastar::future<>)#2}, seastar::future<> >(std::result_of&&, seastar::future<>&&) at /usr/src/debug/scylla-2.2.rc1/seastar/core/future.hh:1307
seastar::future<> seastar::futurize<void>::apply<seastar::rpc::protocol<netw::serializer, netw::messaging_verb>::client::client(seastar::rpc::protocol<netw::serializer, netw::messaging_verb>&, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::{lambda(seastar::future<>)#2}, seastar::future<> >(seastar::rpc::protocol<netw::serializer, netw::messaging_verb>::client::client(seastar::rpc::protocol<netw::serializer, netw::messaging_verb>&, seastar::rpc::client_options, seastar::socket, seastar::ipv4_addr, seastar::ipv4_addr)::{lambda(seastar::future<>)#2}&&, seastar::future<>&&) at /usr/src/debug/scylla-2.2.rc1/seastar/core/future.hh:1355
 (inlined by) _ZZN7seastar6futureIJEE12then_wrappedIZNS_3rpc8protocolIN4netw10serializerENS5_14messaging_verbEE6clientC4ERS8_NS3_14client_optionsENS_6socketENS_9ipv4_addrESD_EUlS1_E0_S1_EET0_OT_ENUlSH_E_clINS_12future_stateIJEEEEEDaSH_ at /usr/src/debug/scylla-2.2.rc1/seastar/core/future.hh:984
 (inlined by) _ZN7seastar12continuationIZNS_6futureIJEE12then_wrappedIZNS_3rpc8protocolIN4netw10serializerENS6_14messaging_verbEE6clientC4ERS9_NS4_14client_optionsENS_6socketENS_9ipv4_addrESE_EUlS2_E0_S2_EET0_OT_EUlSI_E_JEE15run_and_disposeEv at /usr/src/debug/scylla-2.2.rc1/seastar/core/future.hh:413
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-2.2.rc1/seastar/core/reactor.cc:2500
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-2.2.rc1/seastar/core/reactor.cc:2910
seastar::reactor::run_some_tasks() at /opt/scylladb/include/c++/7/chrono:377
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-2.2.rc1/seastar/core/reactor.cc:3057
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /usr/src/debug/scylla-2.2.rc1/seastar/core/reactor.cc:4002
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.2.rc1/seastar/core/posix.cc:52

```

**Comment by slivne** [comment]
@elcallio / @gleb-cloudius rings a bell

**Comment by gleb-cloudius** [comment]
Same as #3457

--
			Gleb.

**Comment by slivne** [comment]
@gleb-cloudius / @elcallio - yet this happens on the 2.2.rc1 node - is this something we are familiar with ?

**Comment by slivne** [comment]
fixed

**Comment by gleb-cloudius** [comment]
It looks like this one is different from #3457 after all and it still happening

**Comment by avikivity** [comment]
Ref scylladb/seastar#474.
