### ISSUE TITLE
Repair process read amplification on the DB with LCS (2.1.4 Scylla version)

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3531]
*Installation details*
Scylla version (or git commit hash): 2.1.4
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)
instance_type_db: i3.4xlarge

Run SCT test on 2.1.4 version, 1T DB (using cassandra-stress prefill) with Level compaction strategy and repair in parallel. During repair significant read amplification was recognized. Repair process for 1T DB takes more then 24 hours and from 5 to 10T data is read while repair process.
Running test monitor: http://54.144.37.49:3000/dashboard/db/scylla-per-server-disk-i-o-2-1
AWS VMs: names are started with "longevity-nocorrupt-7d-2-1-4-loader-node"

When run same scenario on 2.1.2 version, repair process is run 3-4 hours and read 1T of data.
Running test monitor: http://18.207.163.252:3000/dashboard/db/2-1-2-nocorrupt-scylla-per-server-disk-i-o-2-1

**Comment by juliayakovlev** [comment]
@roydahan

**Comment by avikivity** [comment]
Unfortunate side effect of aeffbb6732f9a55434e0772e04d79f207b1cb74d, supposed to happen with Leveled Compaction strategy only. /cc @denesb

**Comment by roydahan** [comment]
I think that this issue combined with #3422 makes this bug severity pretty high.
Every repair that runs on large data set with LCS can take very long time (in our case 1TB dataset took more than 24 hours).

**Comment by denesb** [comment]
Isn't this fixed by f4caa418f? Was this fix backported to 2.1?

**Comment by roydahan** [comment]
I can still see this issue on 2.3.rc1.
A repair of 1.2TB dataset resulted in ~22TB read from one node (took about 14 hours).

![screen shot 2018-08-05 at 14 00 07](https://user-images.githubusercontent.com/20959584/43685233-e97248ee-98b7-11e8-98b3-ccfb1a5ea20f.png)
![screen shot 2018-08-05 at 13 58 40](https://user-images.githubusercontent.com/20959584/43685234-e990602c-98b7-11e8-8f1e-0ea33515d6c5.png)

**Comment by denesb** [comment]
The fix for this landed in 3.0. I think we can close this and reopen if observed with Scylla >= 3.0.

**Comment by avikivity** [comment]
@juliayakovlev / @roydahan please retest

**Comment by raphaelsc** [comment]
ping. looks like we can close this

**Comment by denesb** [comment]
Closing as stale.
