### ISSUE TITLE
error: Invalid yaml. Please remove properties [keyfile, certificate] from your cassandra.yaml

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3550]
*Installation details*
Scylla version (or git commit hash): 2.2.rc2-0.20180621.c11bd3e1c
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

I tried to cleanup keyspace1 at the end of decommission nemesis, but the cmd failed.

```
[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 ~]$ nodetool --host localhost cleanup keyspace1
error: Invalid yaml. Please remove properties [keyfile, certificate] from your cassandra.yaml
-- StackTrace --
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [keyfile, certificate] from your cassandra.yaml
        at org.apache.cassandra.config.YamlConfigurationLoader$MissingPropertiesChecker.check(YamlConfigurationLoader.java:188)
        at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:119)
        at org.apache.cassandra.config.YamlConfigurationLoader.loadConfig(YamlConfigurationLoader.java:95)
        at org.apache.cassandra.config.DatabaseDescriptor.loadConfig(DatabaseDescriptor.java:135)
        at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:119)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.apache.cassandra.config.CFMetaData$Builder.build(CFMetaData.java:1303)
        at org.apache.cassandra.config.CFMetaData.compile(CFMetaData.java:407)
        at org.apache.cassandra.schema.SchemaKeyspace.compile(SchemaKeyspace.java:238)
        at org.apache.cassandra.schema.SchemaKeyspace.<clinit>(SchemaKeyspace.java:88)
        at org.apache.cassandra.config.Schema.<init>(Schema.java:107)
        at org.apache.cassandra.config.Schema.<clinit>(Schema.java:55)
        at org.apache.cassandra.tools.nodetool.Cleanup.execute(Cleanup.java:50)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:265)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:174)

[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 ~]$  echo $?
2


[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 ~]$ nodetool --host localhost describecluster
Cluster Information:
        Name: longevity-ak2-verifier-db-cluster-1963ea61
        Snitch: org.apache.cassandra.locator.SimpleSnitch
        Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
        Schema versions:
                0eacb6e6-a4b3-37e4-b845-0ed0a8e886de: [10.240.0.64, 10.240.0.68, 10.240.0.80, 10.240.0.63]

[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.240.0.64  221.92 MB  256          ?       f6af6f8d-ebc7-46c7-bc86-9441355f069d  rack1
UN  10.240.0.80  222.22 MB  256          ?       d57d72ee-e4c8-470f-ac05-89fdec68f791  rack1
UN  10.240.0.68  169.78 MB  256          ?       a90ac67d-9fe6-4c9d-ac9f-76aaa1adc395  rack1
UN  10.240.0.63  222.37 MB  256          ?       0e70345c-aec7-4af4-b30e-d66c6fa10a83  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 ~]$ scylla --version
2.2.rc2-0.20180621.c11bd3e1c
```

**Comment by amoskong** [comment]
Old server_encryption setup:
```
[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 scylla]$ grep ^server_encryption_options -A 4 scylla.yaml 
server_encryption_options:
   internode_encryption: all
   certificate: /etc/scylla/db.crt
   keyfile: /etc/scylla/db.key
   truststore: /etc/scylla/cadb.pem
```

I commented two parameters, and then the cleanup cmd can succeed.
```
[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 scylla]$ grep ^server_encryption_options -A 4 scylla.yaml 
server_encryption_options:
   internode_encryption: all
   #certificate: /etc/scylla/db.crt
   #keyfile: /etc/scylla/db.key
   truststore: /etc/scylla/cadb.pem
```

```
[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 scylla]$ nodetool --host localhost cleanup keyspace1
[scylla-test@longevity-ak2-verifier-db-node-1963ea61-0-1 scylla]$ echo $?
0
```

**Comment by slivne** [comment]
its strange that nodetool decommission works and nodetool cleanup doesn't

@amoskong  did you run nodetool cleanup on the node that was decomissioned - not likely just checking

@elcallio - I thought we currenctly changed scylla-tools code to disregard configurations it does not know.

**Comment by roydahan** [comment]
@slivne this is not on the node that was decommissioned.
It happens on all nodes that have the keyfile and certificate (IOW has TLS enabled).
reproduces consistently.

**Comment by roydahan** [comment]
@harelassayag @juliayakovlev FYI.

**Comment by amoskong** [comment]
@slivne we run nodetool cleanup after decommission is completed (target node is terminated), the rest nodes and new added node will be cleanup.

**Comment by elcallio** [comment]
Why do you have cassandra.yaml with scylla encryption options in it? It will not work there. 
Did you add this explicitly, or it this in the scripts? We have a feature to copy select options from scylla.yaml if I recall correctly, but if so, why was this copied? 
I only wrote the initial version of said copy script, I have no idea where it even resides now.
We have not in any way changed the cassandra options/parser - we assume we will have reasonably valid options files on disk.

**Comment by roydahan** [comment]
@elcallio, I'm not sure I understand your comment.

We have the scylla.yaml configured with TLS internode encryption based on the documentation we have.
Suddenly, some of the nodetool commands started to fail when we have these parameters in scylla.yaml.

**Comment by elcallio** [comment]
To quote stacktrace: 
```
org.apache.cassandra.exceptions.ConfigurationException: Invalid yaml. Please remove properties [keyfile, certificate] from your cassandra.yaml
        at org.apache.cassandra.config.YamlConfigurationLoader$MissingPropertiesChecker.check(YamlConfigurationLoader.java:188)
```

The java code does not load scylla.yaml (unless someone _really_ told it to explicily). The java code loads cassandra.yaml, which (I think), is kept semi-synced by scripts in a scylla installation, i.e. it will point to data dirs etc. It should however not contain anything about scylla tls or similar. So first thing to check is if the installation cassandra.yaml contains unsolicited entries, and second is to find out who put them there.

**Comment by roydahan** [comment]
I don't know how the mapping between nodetool and scylla.yaml is done.
However, in the test machine I don't have any file called cassandra.yaml:

```
[root@ip-172-16-99-20 /]# find / -name cassandra.yaml
[root@ip-172-16-99-20 /]#
```
And as Amos mentioned above, when commenting out the params from scylla.yaml and running the nodetool command, it works fine.

**Comment by powellchristoph** [comment]
I am running into this myself. The TLS options are place in the `scylla.yaml` per the documentation at http://docs.scylladb.com/operating-scylla/security/node_node_encryption/.

**Comment by roydahan** [comment]
@slivne / @elcallio, can we fix this before branching next release?

**Comment by elcallio** [comment]
See scylladb/scylla-tools-java#70

**Comment by penberg** [comment]
The issue is fixed in:

https://github.com/scylladb/scylla-tools-java/commit/e7d4e4f8aeaae82a3813f942da12817a6019905b

and backported to 3.0 in:

https://github.com/scylladb/scylla-tools-java/commit/8d1383b9935946138028cf4d4a2cd4d9678b15b3

@amoskong @roydahan, I suppose we can close this issue too?

**Comment by amoskong** [comment]
The patch really fixed the problem, we can close this issue.

The latest build master package doesn't contain this patch (scylladb/scylla-tools-java@e7d4e4f), so I can still reproduce this issue with `scylla-tools-666.development-20181009.208b0e2723.el7.noarch & scylla-tools-core-666.development-20181009.208b0e2723.el7.noarch`

I tried to apply this patch (scylladb/scylla-tools-java@e7d4e4f) to /usr/bin/cassandra_attributes.py, then the problem didn't occur.

**Comment by penberg** [comment]
Yes, latest master build will not have it because I just applied it.

Thanks for verifying the fix, @amoskong!

**Comment by penberg** [comment]
The fix is now also backported to 2.3:

https://github.com/scylladb/scylla-tools-java/commit/dab8a52b8a29bc929703ddfa2ca2349f9baeafbe

**Comment by avikivity** [comment]
@penberg please also backport to 2.2, it's still supported, and to enterprise-2018.1 if needed.

**Comment by avikivity** [comment]
Backported to 2.2 as well.

**Comment by avikivity** [comment]
(as 22dd1b1b9c48cd6b802f16740411347b4841b90f)
