### ISSUE TITLE
Non-null component after null component in sstable

### ISSUE THREAD

**Issue by gibsn** [scylladb/scylla#4009]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.rc1
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.4

MC SSTable format, TWCS (1 week window). Have these errors in scylla log:
```
2018-12-20T17:42:29.430627+03:00 beccasc2 scylla: [shard 8] compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable /storage/scylla/becca/events-7c8165f0fdf511e881a5000000000006/mc-11858-big-Data.db)
```

This night we had compaction including this file for the whole time window which ended successfully though.

We have some values in our schema that are not valid UTF8 strings. Can it be the reason?
CQLSH:
```
Failed decoding result column "user" of type varchar: 'utf8' codec can't decode byte 0xa0 in position 0: invalid start byte
```

What are the consequences of this error? Is the whole sstable dropped or only the corrupted cell?

**Comment by slivne** [comment]
@gibsn would it be possible for you to share the sstable and the schema ?

**Comment by gibsn** [comment]
> @gibsn would it be possible for you to share the sstable and the schema ?

I can't share the SSTable since in contains sensitive date

Here is the schema:
{code}
CREATE KEYSPACE ks
    WITH replication = {
        'class': 'NetworkTopologyStrategy',
        'DC1': 1,
        'DC2': 1
    }
AND durable_writes = true;

CREATE TABLE tbl (
    field1 text,
    field2 smallint,
    field3 tinyint,
    field4 timeuuid,
    field5 smallint,
    field6 smallint,
    field7 inet,
    field8 map<text, text>,
    PRIMARY KEY ((field1, field2, field3), field4)
) WITH CLUSTERING ORDER BY (field4 DESC)
    AND bloom_filter_fp_chance = 0.1
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'}
    AND comment = ''
    AND compaction = {
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy',
        'compaction_window_unit': 'DAYS',
        'compaction_window_size': 7
    }
    AND compression = {
        'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor',
        'chunk_length_kb': '64'
    }
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99PERCENTILE';
{code}

**Comment by slivne** [comment]
@gibsn do you have maybe a c-s profile to populate it or some tool we can use to inject data

**Comment by slivne** [comment]
We will attempt to use what you will share to reproduce on 3.0.rc1  - yet since we just released 3.0.rc2 that has many fixes for mc format - can you try and check if it fixes the issue for you

**Comment by avikivity** [comment]
Very strange, non-null component after null component, but there is only one clustering key componet.

**Comment by gibsn** [comment]
> @gibsn do you have maybe a c-s profile to populate it or some tool we can use to inject data

I do have a simple bench script but I guess it won't be useful since we have been using it for testing for about a month and this issue did not show itself.

**Comment by gibsn** [comment]
> We will attempt to use what you will share to reproduce on 3.0.rc1 - yet since we just released 3.0.rc2 that has many fixes for mc format - can you try and check if it fixes the issue for you

How is it supposed to fix it? Is it going to fix the corrupted data, skip the corrupted row/cell or?

**Comment by haaawk** [comment]
As @avikivity said - this is strange because there's only a single field in the clustering key.

@gibsn Would you be able to try running sstabledump on this sstable to see if it complains too?

**Comment by haaawk** [comment]
This could be related maybe: https://github.com/scylladb/scylla/commit/91ce3a795719b15ad828fa8638e6a3a7f86c5976

**Comment by avikivity** [comment]
Unlikely, it should only trigger if you had 16 or more clustering key components.

**Comment by gibsn** [comment]
> @gibsn Would you be able to try running sstabledump on this sstable to see if it complains too?

```
Exception in thread "main" java.lang.NullPointerException
        at org.apache.cassandra.utils.FBUtilities.newPartitioner(FBUtilities.java:447)
        at org.apache.cassandra.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:102)
        at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:20)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:186)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

**Comment by tgrabiec** [comment]
> What are the consequences of this error? Is the whole sstable dropped or only the corrupted cell?`

This error happened during sstable compaction. The compaction will fail and nothing will be changed in the sstables. Next read from that sstable will probably fail in the same way, unless the failure was not due to corruption of the sstable but due to bad process state.

If the bug is in the reader, then after we fix it the data will be recovered. If it was badly written or corrupted then write loss is possible. It could be local to the node, in which case moving the problematic sstable out of the data directory (with the node down) and running repair could recover the writes.

> `Exception in thread "main" java.lang.NullPointerException`

Looks like a config issue, similar to https://github.com/scylladb/scylla-tools-java/issues/25. You can try the workaround from the comment: https://github.com/scylladb/scylla-tools-java/issues/25#issuecomment-316359233

**Comment by gibsn** [comment]
@tgrabiec 

> Looks like a config issue, similar to scylladb/scylla-tools-java#25. You can try the workaround from the comment: scylladb/scylla-tools-java#25 (comment)

Will do

> This night we had compaction including this file for the whole time window which ended successfully though.

I double-checked and actually the number of "big files" (for the whole time window) is not consistent with the number of shards (28 vs 30)

**Comment by tgrabiec** [comment]
On Thu, Dec 20, 2018 at 10:35 PM Kirill Alekseev <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec>
>
> Looks like a config issue, similar to scylladb/scylla-tools-java#25
> <https://github.com/scylladb/scylla-tools-java/issues/25>. You can try
> the workaround from the comment: scylladb/scylla-tools-java#25
> <https://github.com/scylladb/scylla-tools-java/issues/25> (comment)
>
> Will do
>
> This night we had compaction including this file for the whole time window
> which ended successfully though.
>
> That would indicate that the problem was temporary and on the reader side.
If the sstable was successfully compacted, this means you no longer have it
in the data directory, right?

> I double-checked and actually the number of "big files" (for the whole
> time window) is not consistent with the number of shards (28 vs 30)
>
What do you mean by "for the whole time window", do you mean all files in
the data directory, or something else?

**Comment by gibsn** [comment]
@tgrabiec 

>I double-checked and actually the number of "big files" (for the whole
 time window) is not consistent with the number of shards (28 vs 30)

>That would indicate that the problem was temporary and on the reader side.
If the sstable was successfully compacted, this means you no longer have it
in the data directory, right?

Right, but compaction did not finish successfully for all shards, only for 28 out of 30.

> MC SSTable format, TWCS (1 week window)

> What do you mean by "for the whole time window", do you mean all files in
the data directory, or something else?

We use TWCS, "for the whole time window" means major compaction of all data in the given time window

**Comment by gibsn** [comment]
@tgrabiec 

> Looks like a config issue, similar to scylladb/scylla-tools-java#25. You can try the workaround from the comment: scylladb/scylla-tools-java#25 (comment)

Guess it has something to do with the UTF8 validation I mentioned in the beginning

```
Exception in thread "main" java.lang.AssertionError: UTF-8 value contained non-utf8 characters: 
        at org.apache.cassandra.db.marshal.UTF8Type.toJSONString(UTF8Type.java:70)
        at org.apache.cassandra.tools.JsonTransformer.serializeCell(JsonTransformer.java:468)
        at org.apache.cassandra.tools.JsonTransformer.serializeColumnData(JsonTransformer.java:397)
        at org.apache.cassandra.tools.JsonTransformer.serializeRow(JsonTransformer.java:277)
        at org.apache.cassandra.tools.JsonTransformer.serializePartition(JsonTransformer.java:211)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.apache.cassandra.tools.JsonTransformer.toJson(JsonTransformer.java:101)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:248)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
        at org.apache.cassandra.utils.ByteBufferUtil.string(ByteBufferUtil.java:156)
        at org.apache.cassandra.db.marshal.UTF8Type.toJSONString(UTF8Type.java:66)
        ... 17 more
```

**Comment by tgrabiec** [comment]
On Fri, Dec 21, 2018 at 3:47 PM Kirill Alekseev <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec>
>
> I double-checked and actually the number of "big files" (for the whole
> time window) is not consistent with the number of shards (28 vs 30)
>
> That would indicate that the problem was temporary and on the reader side.
> If the sstable was successfully compacted, this means you no longer have it
> in the data directory, right?
>
> Right, but compaction did not finish successfully for all shards, only for
> 28 out of 30.
>
What was the cause of failure this time (log message)?

**Comment by gibsn** [comment]
> What was the cause of failure this time (log message)?

Same, it can not compact some SSTables, sleeps and starts again

**Comment by tgrabiec** [comment]
On Fri, Dec 21, 2018 at 4:41 PM Kirill Alekseev <notifications@github.com>
wrote:

> What was the cause of failure this time (log message)?
>
> Same, it can not compact some SSTables, sleeps and starts again
>
With exactly the same error message ("non-null component ...")?

**Comment by tgrabiec** [comment]
On Fri, Dec 21, 2018 at 3:49 PM Kirill Alekseev <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec>
>
> Looks like a config issue, similar to scylladb/scylla-tools-java#25
> <https://github.com/scylladb/scylla-tools-java/issues/25>. You can try
> the workaround from the comment: scylladb/scylla-tools-java#25
> <https://github.com/scylladb/scylla-tools-java/issues/25> (comment)
>
> Guess it has something to do with the UTF8 validation I mentioned in the
> beginning
>

Yes, though it doesn't explain the compaction failure, since we do no
string validation on compaction.

Can try to run sstabledump with -d option, it will not generate a JSON.

**Comment by gibsn** [comment]
> Can try to run sstabledump with -d option, it will not generate a JSON.

```
Exception in thread "main" org.apache.cassandra.serializers.MarshalException: String didn't validate.
        at org.apache.cassandra.serializers.UTF8Serializer.validate(UTF8Serializer.java:35)
        at org.apache.cassandra.db.marshal.AbstractType.getString(AbstractType.java:131)
        at org.apache.cassandra.db.rows.AbstractCell.toString(AbstractCell.java:199)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.apache.cassandra.db.rows.AbstractRow.toString(AbstractRow.java:145)
        at org.apache.cassandra.tools.SSTableExport.lambda$null$5(SSTableExport.java:241)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at org.apache.cassandra.tools.SSTableExport.lambda$run$6(SSTableExport.java:237)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:223)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

**Comment by gibsn** [comment]
Got a new error today on single node single shard:
{code}
beccasc4/scylla.log-2018.12.26-02:2018-12-26T01:54:11.469716+03:00 beccasc4 scylla: [shard 27] compaction_manager - compaction failed: sstables::malformed_sstable_exception (Too big ttl: 1410261982 in sstable /storage/scylla/becca/events-7c8165f0fdf511e881a5000000000006/mc-33177-big-Data.db)
{code}

**Comment by avikivity** [comment]
@gibsn 

> > @gibsn do you have maybe a c-s profile to populate it or some tool we can use to inject data
> 
> I do have a simple bench script but I guess it won't be useful since we have been using it for testing for about a month and this issue did not show itself.

Does that mean you tested mc format with rc1 or earlier? What's the earliest git hash that you tested with?

It's possible those older versions generated bad sstables.

**Comment by avikivity** [comment]
@gibsn I see. If you can please clear the data and try with rc3.

**Comment by avikivity** [comment]
make sure to shut down the cluster completely before deleting the sstables.

**Comment by gibsn** [comment]
> make sure to shut down the cluster completely before deleting the sstables.

truncating won't help? should we `rm -rf` all data and start with a new cluster?

**Comment by avikivity** [comment]
Well, truncating should work but let's be extra careful.

Either would work:

1. shutdown + rm -rf /var/lib/scylla/data/your_keyspaces /var/lib/scylla/commitlog + start
2. new cluster with wiped data partititions

The former saves you from having to recreate the schema.

**Comment by slivne** [comment]
On Wed, Dec 26, 2018 at 5:36 PM Avi Kivity <notifications@github.com> wrote:

> Well, truncating should work but let's be extra careful.
>
> Either would work:
>
>    1. shutdown + rm -rf /var/lib/scylla/data/your_keyspaces
>    /var/lib/scylla/commitlog + start
>
> there are also hints nowadays (as of 3.0 they are enabled by default)

so please also erase  the hints /var/lib/scylla/hints

**Comment by gibsn** [comment]
@avikivity @slivne 

We will update to rc3 tomorrow, see what changes. Then [most probably] we will erase all data and start with a new cluster

**Comment by gibsn** [comment]
We have updated to rc3, but nothing changed. We have erased all data and started with a new cluster

**Comment by tgrabiec** [comment]
By "nothing changed", you mean that you're still getting those `malformed_sstable_exception`?

How long does it take to reproduce?

Once you get them, do you get them each time you do `nodetool cleanup` on that table, for the same sstable?

Does it reproduce with `enable_sstables_mc_format` disabled?

What kind of insert/update statements are executed on that table?

**Comment by gibsn** [comment]
>By "nothing changed", you mean that you're still getting those malformed_sstable_exception?

Yes

> How long does it take to reproduce?

What do you mean by reproduce? We had been getting those errors in the live cluster constantly on the same SSTables. I am not sure how to reproduce malformed SSTables.

> Once you get them, do you get them each time you do nodetool cleanup on that table, for the same sstable?
Does it reproduce with enable_sstables_mc_format disabled?

Can't say, we erased all the data. Now it's been a couple of days with rc3 and no compaction errors so far.

> What kind of insert/update statements are executed on that table?

Just inserts with no TTL or timestamp

**Comment by haaawk** [comment]
@gibsn when you said "We have some values in our schema that are not valid UTF8 strings", did you mean you have names of fields or tables that are not UTF-8 strings or that you have some text fields that you set value to not UTF-8 strings?

Do you still have this sstable that caused the following error "non-null component after null component" ? It was /storage/scylla/becca/events-7c8165f0fdf511e881a5000000000006/mc-11858-big-Data.db

**Comment by haaawk** [comment]
Also do you have any range_tombstones in that sstables?

**Comment by haaawk** [comment]
"Exception in thread "main" org.apache.cassandra.serializers.MarshalException: String didn't validate." happens for a cell in a collection so I guess it has to be non-utf8 value in field8 map<text, text> as this is the only collection in the table.

Would you be able to run a test with field8 removed/unused? There's a pretty big chance that non-utf8 keys in the map are problematic.

**Comment by gibsn** [comment]
> when you said "We have some values in our schema that are not valid UTF8 strings", did you mean you have names of fields or tables that are not UTF-8 strings or that you have some text fields that you set value to not UTF-8 strings?

Second

> Also do you have any range_tombstones in that sstables?

No, we have no deletes and no TTL

> Would you be able to run a test with field8 removed/unused? 

You mean on the existing SSTable? How can I do that? Maybe I can provide a different schema to `sstabledump`?

**Comment by haaawk** [comment]
I mean try to run cluster without populating the map field and see if you still see the problem. Ideally you could just remove that map field from the schema for the test but not populating it should work as well. If the issue is with the collection field then your cluster should work correctly with no problems after you remove/don't use collection field.

**Comment by gibsn** [comment]
> If the issue is with the collection field then your cluster should work correctly with no problems after you remove/don't use collection field

I need to use this field. Actually trying to insert non valid UTF8 is a bug which should be fixed

> I mean try to run cluster without populating the map field

The workload is live, I don't know how much to wait till the problem shows itself, this time it took 1 week. Also this way requires editing and deploying production services. Maybe we'd better try to reproduce?

**Comment by gibsn** [comment]
Should you respond with error in case client is trying to insert non-utf8 to the text field? If the bug is confirmed, what are the chances the fix will be taken to the 3.0.0 release?

**Comment by haaawk** [comment]
> Should you respond with error in case client is trying to insert non-utf8 to the text field? If the bug is confirmed, what are the chances the fix will be taken to the 3.0.0 release?

I think we already validate that but let me double check.

> The workload is live, I don't know how much to wait till the problem shows itself, this time it took 1 week. Also this way requires editing and deploying production services. Maybe we'd better try to reproduce?

Sure. I didn't know your setup so I asked in case that maybe it's easy for you to run those types of experiments. If not that's fine too. So far we were not able to reproduce this problem that's why I'm looking for other ways to investigate it.

**Comment by haaawk** [comment]
BTW how do you manage to send nonutf8 strings to scylla anyway? Are you using cqlsh or a driver? If driver which language?

**Comment by gibsn** [comment]
I am using gocql

**Comment by gibsn** [comment]
In 3.0.rc3 cluster we are getting this error during compaction:
```
2019-01-10T17:04:30.446182+03:00 beccasc2 scylla: [shard 9] compaction_manager - compaction failed: sstables::malformed_sstable_exception (Too big ttl: 3637411336 in sstable /storage/scylla/becca/events-7fc169a009c511e9a424000000000006/mc-22749-big-Data.db)
```


```
sstabledump -d /storage/scylla/becca/events-7fc169a009c511e9a424000000000006/mc-22749-big-Data.db
Exception in thread "main" org.apache.cassandra.serializers.MarshalException: String didn't validate.
        at org.apache.cassandra.serializers.UTF8Serializer.validate(UTF8Serializer.java:35)
        at org.apache.cassandra.db.marshal.AbstractType.getString(AbstractType.java:131)
        at org.apache.cassandra.db.rows.AbstractCell.toString(AbstractCell.java:198)
        at java.lang.String.valueOf(String.java:2994)
        at java.lang.StringBuilder.append(StringBuilder.java:131)
        at org.apache.cassandra.db.rows.AbstractRow.toString(AbstractRow.java:145)
        at org.apache.cassandra.tools.SSTableExport.lambda$null$5(SSTableExport.java:241)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at org.apache.cassandra.tools.SSTableExport.lambda$run$6(SSTableExport.java:237)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:223)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

**Comment by gibsn** [comment]
I was able to insert non-utf8 to map<text, text> both as key and value using gocql, could not reproduce compaction fail though
3.0.rc3

**Comment by haaawk** [comment]
@gibsn Do you still have this sstable that caused:
```
non-null component after null component in sstable /storage/scylla/becca/events-7c8165f0fdf511e881a5000000000006/mc-11858-big-Data.db
```
?

**Comment by gibsn** [comment]
>Do you still have this sstable that caused:
non-null component after null component in sstable /storage/scylla/becca/events-7c8165f0fdf511e881a5000000000006/mc-11858-big-Data.db
?

yes

**Comment by haaawk** [comment]
Would you be willing to share *-Statistics.db file for it @gibsn? This one does not contain data only statistics of the file.

**Comment by gibsn** [comment]
@haaawk I have only "Data" file. However I do have Statistics.db for `2019-01-10T17:04:30.446182+03:00 beccasc2 scylla: [shard 9] compaction_manager - compaction failed: sstables::malformed_sstable_exception (Too big ttl: 3637411336 in sstable /storage/scylla/becca/events-7fc169a009c511e9a424000000000006/mc-22749-big-Data.db)`

**Comment by haaawk** [comment]
@gibsn The other one would be better but if we don't have it then even the one you have can be useful. Could you either post it here or send it to piotr@scylladb.com please?

**Comment by gibsn** [comment]
@haaawk sent via email

**Comment by slivne** [comment]
So to summarize - the issue is that we are able to write non utf-8 in text fields via the go driver.

@haaawk  / @gibsn - if you have sample code doing that it will be great - so we will not need to attempt to find the how.

In any case I am reassigning this.

**Comment by haaawk** [comment]
I've got a fix that adds validation on Scylla side but didn't have time to figure out how to reproduce the problem @slivne. Java driver ensures utf8 correctness at very low level.

**Comment by gibsn** [comment]
@slivne I am using gocql from master, revision e06f8c1bcd787e6bf0608288b314522f08cc7848
Inserting non-valid utf8 string can be done directly
`session.Query("INSERT INTO ks.cf(map) VALUES (?)").Bind(string([]byte{0xff})).Exec()`

**Comment by haaawk** [comment]
I reproduced the problem with scylla using @gibsn go code.
It accepts the insert but on select it fails with:
```
Traceback (most recent call last):
  File "/usr/bin/cqlsh", line 1032, in perform_simple_statement
    result = future.result()
  File "cassandra/cluster.py", line 4033, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
DriverException: Failed decoding result column "v" of type map<varchar, varchar>: 'utf8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by tgrabiec** [comment]
On Sun, Jan 27, 2019 at 9:46 AM Shlomi Livne <notifications@github.com>
wrote:

> So to summarize - the issue is that we are able to write non utf-8 in text
> fields via the go driver.
>
> @haaawk <https://github.com/haaawk> / @gibsn <https://github.com/gibsn> -
> if you have sample code doing that it will be great - so we will not need
> to attempt to find the how.
>
> In any case I am reassigning this.
>

There are 2 issues. One is the one you mentioned, which makes
sstabledump complain. The other is that for some sstables our parser
throws sstables::malformed_sstable_exception. The latter seems unrelated,
since utf8 values are treated as blobs by the sstable writer and parser.

**Comment by haaawk** [comment]
I sent a patch that will make Scylla validate those strings and not accept non-UTF-8 bytes.

**Comment by gibsn** [comment]
We have deployed strings validation and will not send non-utf8 strings to Scylla. We will erase the cluster and start over again and will see if anything changes

**Comment by tgrabiec** [comment]
Commit  85409c1 probably doesn't fix the `malformed_sstable_exception (non-null component after null component ...` error, right?

**Comment by haaawk** [comment]
Depends whether it was a result of undefined behavior caused by non-utf text but probably you're right and the commit fixes only part of this issue.
