### ISSUE TITLE
scylla_prepare: Failed to write into /proc/irq/412/smp_affinity: (<class 'OSError'>, OSError(5, 'Input/output error'),

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4057]
*Installation details*
Scylla version (or git commit hash): 3.0.rc4-0.20190106.5a178ff63
Cluster size: 1
Instance type: i3.metal
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-093fc065976f6227b

* Description: I saw many write errors in scylla-prepare log: 

`Failed to write into /proc/irq/412/smp_affinity: (<class 'OSError'>, OSError(5, 'Input/output error'), <traceback object at 0x7f1df3163808>`

* Test log: http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-ami-test/label=muninn/52/artifact/latest/job.log

* Completed AMI-setup, prepare, start log:
[ami-setup-prepare-log.txt](https://github.com/scylladb/scylla/files/2731427/ami-setup-prepare-log.txt)

* The error exists with 3.0-rc3

**Comment by slivne** [comment]
@vladzcloudius help ...

**Comment by avikivity** [comment]
@vladzcloudius we should skip the i3-specific tuning on i3.metal.

**Comment by avikivity** [comment]
Introduced by 8ecb528d5a8268fa65e6c6d55ce3f22bdca417d3.

**Comment by vladzcloudius** [comment]
@slivne This errors have always been there - this is due to read-only nature of NVMe smp_affinity files on bare-metal (and KVM) machines. Writing into them has no effect and these messages should be ignored.
@avikivity These are not i3-specific tuning - this is an regular tuning of NVMe IRQs which we always do which has no negative effect when `smp_affinity` files are read-only like on i3.metal. This hasn't been recently introduced behaviour but rather the behaviour that was there all the time we introduced disks tuning.

**Comment by avikivity** [comment]
@vladzcloudius I think those files will be read-only on anything that isn't Xen, so it is i3.nonmetal specific.

At the very least we should not emit the errors, but I think it's better not to mess with interrupts on non-i3 machines.

**Comment by vladzcloudius** [comment]
@avikivity We can't be 100% these are going to be read-only on anything but XEN for the same reason it's not like that on XEN - it may just be that way. We can't control it and it may change in future too. IMO we should always tune it. 
We have already discussed this already on the " [seastar-dev] [PATCH v1 0/2] scripts: perftune.py: support different I/O schedulers" thread. I sent a message to the maintainer but got no answer so far. 

The situation right now is that there are cases when we know that tuning *should be* done by the kernel but there is no way to make sure it's actually the case except for actually trying to tune it yourself (and fail). And of course there is a case where we know that it's broken (i3.nonmetal). 

IMO the safest is to always try to tune it. We can conceal errors for i3.nonmetal machines but I'm afraid that by doing this we may miss real issues. It's easier to debug things when we see the whole picture. Maybe I should add an extra parameter for the `perftune.py` which would log such failed writes and have them concealed by default. @avikivity Would it be acceptable?

**Comment by vladzcloudius** [comment]
@slivne On top of all said above, please, note that this issue is not a "bug" but rather an "annoyance".

**Comment by avikivity** [comment]
We'll keep seeing this reported. Better to swallow the exception.

**Comment by vladzcloudius** [comment]
@avikivity Right. That's exactly what I suggested above: swallow them by default (amis/rpms/deb will run a default config) and if the new parameter will be given only then show them (this could be done during the debug session by manual `perftune.py`  invocation).

**Comment by vladzcloudius** [comment]
@avikivity A small clarification: the exception has been "swallowed" from day0 - it's just I was logging it unconditionally and continued. I'm preparing a patch that would silence it for NVMe IRQs tuning by default.

**Comment by amoskong** [comment]
Is this issue fixed by https://github.com/scylladb/seastar/commit/cf2873346f9fefea2e9684cb5cee0e32f2aca7fb ?

- The issue still exist in http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/ami-tests/label=muninn/15/artifact/latest/job.log
- Version: 666.development-0.20190122.dbc1894bd
- AMI: ami-07240f76813031542

**Comment by vladzcloudius** [comment]
@amoskong Yes. The patch above is supposed to fix this. However the `seastar` tip that corresponds to dbc1894bd scylla HEAD still doesn't have it that's why you still see these messages.

**Comment by slivne** [comment]
@amoskong I think this is merged now - can you confirm this is fixed and we can close

**Comment by amoskong** [comment]
Master: N/a (no new ami for testing):
- http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/ami/

Problem still exists in 3.0.4-0.20190313.5e3a52024
- http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-ami-test/label=muninn/87/artifact/job-2019-03-13T17.40-7d0524a/job.log

**Comment by vladzcloudius** [comment]
> Problem still exists in 3.0.4-0.20190313.5e3a52024
> 
>     * http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/3.0-test/job/scylla-ami-test/label=muninn/87/artifact/job-2019-03-13T17.40-7d0524a/job.log


@amoskong That's expected since the fix is not a part of 3.0.4

**Comment by amoskong** [comment]
Update: 
* master
  - still no available ami for testing
* 3.0:
  - problem exists with 3.0.5-0.20190329.5ec646cb4
  - Question: can someone update this issue when the fix is backported to 3.0?

**Comment by slivne** [comment]
@amoskong lets validate on 3.1.

**Comment by amoskong** [comment]
> @amoskong lets validate on 3.1.

Problem still exists in 3.1.0.rc2-0.20190617.7d14514b8

http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/ami-tests/33/label=muninn/artifact/latest/job.log

**Comment by vladzcloudius** [comment]
@slivne @avikivity There was a bug in the regexpr in the patch above. I sent a fix and the patch is on the mailing list: " [seastar-dev] [PATCH v1] perftune.py: fix the i3 metal detection pattern"

**Comment by amoskong** [comment]
Thanks,
Thanks, I will test the patch.

vladzcloudius <notifications@github.com> 于 2019年6月21日周五 上午2:41写道：

**Comment by amoskong** [comment]
Test result: Vlad's patch fixed the issue.

**Comment by tzach** [comment]
@amoskong @vladzcloudius can we close this issue?

**Comment by amoskong** [comment]
We need this fix for 3.1 & 2019.1?

Tzach Livyatan <notifications@github.com> 于 2019年6月23日周日 下午3:06写道：

**Comment by amoskong** [comment]
> We need this fix for 3.1 & 2019.1? 

@slivne @tzach  It seems the patch isn't backported to branch-3.1

**Comment by slivne** [comment]
now its backported - closing the issue
