### ISSUE TITLE
test.py should provide an option to create xml file in xunit format

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4680]
To help track the unit tests results we should integrate the unit test results with Jenkins.
We would benefit greatly by tracking unit test failures in the next-gating jobs to quickly see which unit tests failed and analyze their history to find out when they became flaky, for example.

It seems like the easiest way to achieve that is to have an option in `test.py` to create a xml file in the [xunit format](https://nose.readthedocs.io/en/latest/plugins/xunit.html), like we do for dtests and collect it to the test artifacts in Jenkins.

**Comment by bhalevy** [comment]
Cc @hagitsegev

**Comment by hagitsegev** [comment]
Please let me know when you do the test.py trick, and I'll set the jenkins magic.

**Comment by bhalevy** [comment]
Cc @haaawk

**Comment by hagitsegev** [comment]
@kbr- I can't test it on BYO, as I can't change scylla rtpo there.
Could you please push your branch to seastar-dev (e.g. called `kbr/testsxml`).
This is because of the contents of `.gitmodules` in the root of the tree that uses relative urls so all submodule repos need to be there on the same github account

**Comment by kbr-** [comment]
@hagitsegev I assumed you meant scylla-dev, is this ok?:
https://github.com/scylladb/scylla-dev/tree/kbr/testsxml

**Comment by haaawk** [comment]
@kbr- Nope. @hagitsegev mentioned seastar-dev. That's the repo used by default in our BYO tests.

**Comment by haaawk** [comment]
Here's the URL: https://github.com/scylladb/seastar-dev

**Comment by kbr-** [comment]
Ok.
https://github.com/scylladb/seastar-dev/tree/kbr/testsxml

**Comment by hagitsegev** [comment]
Thanks. Testing: https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/452/

**Comment by hagitsegev** [comment]
Expecting Ant GLOB pattern, but saw '/jenkins/workspace/scylla-master/manual-and-scheduled-tests/byo_build_tests_dtest/unittests.xml
I gave it "unittests.xml" as the file name. Looks like it expects something else...
@kbr-

**Comment by kbr-** [comment]
@hagitsegev it looks like python's ElementTree.write function doesn't like absolute paths.
I fixed it now.

**Comment by hagitsegev** [comment]
@kb Still fails.
20:13:14    File "./test.py", line 344, in <module>
20:13:14      with open(args.xunit, "w") as f:
20:13:14  PermissionError: [Errno 13] Permission denied: '/data/jenkins/workspace/scylla-master/manual-and-scheduled-tests/byo_build_tests_dtest/unittests.xml'

The location is OK, I don't know why permission denied there.
http://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/453/console

**Comment by hagitsegev** [comment]
@kbr- Any news?

**Comment by kbr-** [comment]
@hagitsegev not yet, I'll investigate the issue tomorrow.

**Comment by kbr-** [comment]
So it turned out that we don't need to create an xml file with all test results, since every boost test already creates an xml file.
But non-boost tests don't, and the above pull request changes it.

**Comment by kbr-** [comment]
Example results:
![image](https://user-images.githubusercontent.com/6516501/61727172-267bc280-ad73-11e9-8f47-f497d7c9283c.png)
(ignore test1, test2, and unit tests row, they are artifacts from previous testing runs, will be gone after some time)

See https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/test_results_analyzer/.

**Comment by hagitsegev** [comment]
build system related changed are on https://github.com/scylladb/scylla-pkg/pull/469

**Comment by penberg** [comment]
@bentsi @kbr- What tests in `test.py` are _not_ using Boost Test? I only see this:

```
other_tests = [
    'memory_footprint',
]
```

**Comment by kbr-** [comment]
See also line 236

**Comment by penberg** [comment]
Aah, right, LSA and row cache tests. Thanks for the clarification, @kbr-!

**Comment by kostja** [comment]
The implementation produces currently 102 output files while the harness runs 108 tests. This is because the output file name is derived from the test name, and there are tests which are run multiple times, in different configurations.
