### ISSUE TITLE
branch next-3.1 build failure

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla#4834]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): next-3.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Gentoo Linux

Build tools details:
- x86_64-pc-linux-gnu-8.3.0
- boost-1.65 patched to support GCC 7.1
- thrift 0.9.3

Hey guys, I'm trying to debug a build failure on the next-3.1 branch please.

Please note that 3.0.9 builds okay with the same build tools.

Attaching build.log

**Comment by ultrabug** [comment]
[build.log](https://github.com/scylladb/scylla/files/3492719/build.log)

**Comment by avikivity** [comment]
Which version of fmt do you have? We build with 5.2 or so.

Note you can build with a packaged toolchain that is independent from the host, see https://github.com/scylladb/scylla/blob/master/tools/toolchain/README.md.

**Comment by ultrabug** [comment]
@avikivity libfmt-5.3.0

Thanks for the dbuild link, thing is that on Gentoo we rely on the local toolchain so I can't rely on users having a working docker as a dependency to build their scylla package (even more on servers).

I'll search for the dbuild source code tho as it will surely provide some interesting information from a packager's perspective!

**Comment by avikivity** [comment]
I'll try to fix it for libfmt 5.3.

**Comment by avikivity** [comment]
I think it was already fixed by @vladzcloudius, try cherry-picking 5632c0776e5786c270b4c594ccb7cc3303e1648a on top of 3.1.

**Comment by ultrabug** [comment]
Testing

**Comment by ultrabug** [comment]
Nah still failing @avikivity sorry. (btw this commit targets test/ files, I guess this might be why?)

Tried compiling with fmt 5.2.0 and still the same problem... gonna try with older fmt

**Comment by ultrabug** [comment]
Ok so :

- dev-libs/libfmt-5.1.0 KO
- dev-libs/libfmt-5.2.0 KO
- **dev-libs/libfmt-5.2.1 OK**
- dev-libs/libfmt-5.3.0 KO

So I'm gonna force on 5.2.1 for now

**Comment by vladzcloudius** [comment]
@ultrabug There were a few other fixes like this:
```
git log --oneline | grep "fix the compilation with fmt v5.3.0"
5632c0776 tests: fix the compilation with fmt v5.3.0
fe82437de types.cc: fix the compilation with fmt v5.3.0
afa176851 transport: result_message: fix the compilation with fmt v5.3.0
```

**Comment by ultrabug** [comment]
I see @vladzcloudius, unfortunately those do not backport properly on `next-3.1` :/

Will have a look, but at least that means that master should build on 5.3.0

**Comment by ultrabug** [comment]
Ok, it's because `afa176851` is part of `next-3.1`...

**Comment by vladzcloudius** [comment]
> I see @vladzcloudius, unfortunately those do not backport properly on `next-3.1` :/
> 
> Will have a look, but at least that means that master should build on 5.3.0

@ultrabug I'm using fmt 5.3.0 in my environment, so, yes, it builds just fine.

**Comment by ultrabug** [comment]
Indeed, add the two other commits to a patch and builds good. Will include this in my packaging until the next major release!

Thanks!
