### ISSUE TITLE
CDC: wrong value for set in cdc_log table after second insert

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6084]
*Installation details*
scylla-release: 0.20200325.78f5afec30
scylla-version: 4.0.rc0
scylla-BuildID[sha1]: 6a210b1adac28793113c61e037cdd06040f0d217
Scylla version (or git commit hash):
Cluster size: 1

table configured with value column as set<text> and cdc postimage enabled. After inserting twice same row, postimage row contains empty value:
```
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1} ;
cqlsh> CREATE TABLE ks.cf (pkey int, ckey int, value list<int>, PRIMARY KEY (pkey, ckey)) WITH cdc={'enabled': true, 'postimage': true};
cqlsh> DROP TABLE ks.cf
   ... ;
cqlsh> CREATE TABLE ks.cf (pkey int, ckey int, value set<text>, PRIMARY KEY (pkey, ckey)) WITH cdc={'enabled': true, 'postimage': true};
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, {"value1", "value2"});
SyntaxException: line 1:52 no viable alternative at input '{'
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, \{"value1", "value2"\});
Invalid syntax at line 1, char 53
  INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, \{"value1", "value2"\});
                                                      ^
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, {"value1", "value2"});
SyntaxException: line 1:52 no viable alternative at input '{'
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, { 'value1', 'value2'});
cqlsh> SELECT * FROM ks.cf
cf                 cf_scylla_cdc_log  
cqlsh> SELECT * FROM ks.cf_scylla_cdc_log ;

 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 |                0 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}

(6 rows)
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, { 'value1', 'value2'});
cqlsh> SELECT * FROM ks.cf_scylla_cdc_log ;

 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 |                0 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b5a-6f20-11ea-4c32-73a08a236811 |                0 |                       null |              null |             0 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b5a-6f20-11ea-4c32-73a08a236811 |                1 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b5a-6f20-11ea-4c32-73a08a236811 |                2 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                0 |                       null |              null |             0 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                1 |                       null |              null |             2 |    null |    1 |    1 |                 null
>>>WRONG VALUE>>>>0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                2 |                       null |              null |             9 |    null |    1 |    1 |       {'', 'value1'}<<<<<
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                3 |                       null |              null |             0 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                4 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                5 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}

(15 rows)
```

**Comment by haaawk** [comment]
```
 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 |                0 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
```

This is confusing. Why a single insert is represented as 2 operations? There are two distinct cdc$time 36976f1a-6f20-11ea-c953-f6fb8f2d34a5 and 36976f24-6f20-11ea-94ca-5ce3c02b9709. I guess that this could be because setting a collection is first removing it and then updating but why can't this be a single operation (same cdc$time) and just different rows (different batch_seq_no)? 

```
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 36976f24-6f20-11ea-94ca-5ce3c02b9709 |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
```
here for 36976f24-6f20-11ea-94ca-5ce3c02b9709 we have 4 rows: insert, postimage, update, postimage. Why is the insert empty? What do we need the update for? Can't insert contain the value that's being set? @kbr- is this somehow related to splitting?

There's a similar story with the second insert. it generates two operations and for the second operation it's both insert and update. update has the right value but insert has bogus data. @elcallio Could this be a bug in collections handling?
```
0x31be5747eefc68b185b1b5812701c5d1 | 46588b5a-6f20-11ea-4c32-73a08a236811 |                0 |                       null |              null |             0 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b5a-6f20-11ea-4c32-73a08a236811 |                1 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b5a-6f20-11ea-4c32-73a08a236811 |                2 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                0 |                       null |              null |             0 |    null |    1 |    1 |                 null
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                1 |                       null |              null |             2 |    null |    1 |    1 |                 null
>>>WRONG VALUE>>>>0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                2 |                       null |              null |             9 |    null |    1 |    1 |       {'', 'value1'}<<<<<
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                3 |                       null |              null |             0 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                4 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x31be5747eefc68b185b1b5812701c5d1 | 46588b64-6f20-11ea-ead1-ca68aecd025e |                5 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
```

**Comment by haaawk** [comment]
It seems that the problem is that we create multiple postimage's for a single operation. I think it would be better to have no more than one preimage and one postimage under a single cdc$time

**Comment by haaawk** [comment]
After some more thinking, it seems that the problem is that we split insert into multiple rows. The fix probably would be to just have a single operation for insert.

**Comment by jul-stas** [comment]
After researching with @piodul we conclude that:
- you have 2 issues here: one is unnecessary preimage, the other is splitting of collection writes
- both are already fixed on master:
```
 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0x68fcd0e2c7b13734a84e54f375e73743 | 06153be6-8aba-11ea-9185-1a9d95265cd9 |                0 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06153be6-8aba-11ea-9185-1a9d95265cd9 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06153bf0-8aba-11ea-0d0a-f08106f85b62 |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06153bf0-8aba-11ea-0d0a-f08106f85b62 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06153bf0-8aba-11ea-0d0a-f08106f85b62 |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x68fcd0e2c7b13734a84e54f375e73743 | 06153bf0-8aba-11ea-0d0a-f08106f85b62 |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
 0x68fcd0e2c7b13734a84e54f375e73743 | 06561f08-8aba-11ea-c5da-ffeb7a034b09 |                0 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06561f08-8aba-11ea-c5da-ffeb7a034b09 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06561f12-8aba-11ea-7d1d-3db6c5f316ca |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06561f12-8aba-11ea-7d1d-3db6c5f316ca |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x68fcd0e2c7b13734a84e54f375e73743 | 06561f12-8aba-11ea-7d1d-3db6c5f316ca |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x68fcd0e2c7b13734a84e54f375e73743 | 06561f12-8aba-11ea-7d1d-3db6c5f316ca |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
```
- The fix is a conjunction of 3 patches by Calle:
881ebe192b8ab901850838965bb1a03ecfbf78ed
532a8634c6fcdb909afcc28108bb3f67286221c8
65a6ebbd73c99df329591455a372c9a6aea3e06b

**Comment by haaawk** [comment]
What's the result if you enable preimage? @jul-stas

**Comment by haaawk** [comment]
There's still an issue that we have multiple postimages per single cdc$time. We should have at most one preimage and one postimage for each cdc$time

**Comment by jul-stas** [comment]
> What's the result if you enable preimage? @jul-stas
It's generally OK, but appears twice on second INSERT.

Speaking of multiple postimages - we thought that it's beyond the scope of this task, but we also agreed to continue the pair programming session at 15:00 today, so we can have a look into that. 

```
 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0x9867b3a367e59fd0733f33b4383eb926 | 4d3851d4-8aba-11ea-cef3-dd7eb8701961 |                0 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d3851d4-8aba-11ea-cef3-dd7eb8701961 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d3851de-8aba-11ea-3e79-66bd65ceb4e0 |                0 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d3851de-8aba-11ea-3e79-66bd65ceb4e0 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d3851de-8aba-11ea-3e79-66bd65ceb4e0 |                2 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x9867b3a367e59fd0733f33b4383eb926 | 4d3851de-8aba-11ea-3e79-66bd65ceb4e0 |                3 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c042-8aba-11ea-d8b7-f59bb80c1426 |                0 |                       null |              null |             0 |    null |    1 |    1 | {'value1', 'value2'}
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c042-8aba-11ea-d8b7-f59bb80c1426 |                1 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c042-8aba-11ea-d8b7-f59bb80c1426 |                2 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c04c-8aba-11ea-ae01-fa5e2f55d148 |                0 |                       null |              null |             0 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c04c-8aba-11ea-ae01-fa5e2f55d148 |                1 |                       null |              null |             2 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c04c-8aba-11ea-ae01-fa5e2f55d148 |                2 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c04c-8aba-11ea-ae01-fa5e2f55d148 |                3 |                       null |              null |             0 |    null |    1 |    1 |                 null
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c04c-8aba-11ea-ae01-fa5e2f55d148 |                4 |                       null |              null |             1 |    null |    1 |    1 | {'value1', 'value2'}
 0x9867b3a367e59fd0733f33b4383eb926 | 4d79c04c-8aba-11ea-ae01-fa5e2f55d148 |                5 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
```

**Comment by piodul** [comment]
@haaawk Together with @jul-stas, we came to the following conclusions:

We can't, in general, have at most one pre/post row for single cdc$time. One cdc$time may correspond to a batch, which may change several rows. The best we can do is to have one pre/post row for each row changed.

This issue is partially resolved by the fact that we already do "splitting" of the batch (for the uninitiated, introduced [here]()). We split it into parts, where each part corresponds to a change that can be represented by a CQL statement. Each part is translated to a CDC log row with insert/update/remove operation, and each such row may be prepended by preimage row and/or followed by postimage row.

Each generated part modifies only one base table row, but multiple parts may modify the same row. Some examples include:

- Two parts will be generated when two atomic fields are updated, but with different TTL,
- INSERT of non-frozen collection will generate two parts: one insert for the row marker, and one update to add new fields (@kbr- please correct me if I'm wrong).

We could try to add logic for merging preimage and postimage rows that touch the same part into one, but we think we do the the refactor of transformer::transform first (https://github.com/scylladb/scylla/issues/5945).

**Comment by haaawk** [comment]
@piodul @jul-stas @kbr- what's the status of this? Have we fixed all the issues here?

**Comment by jul-stas** [comment]
To my knowledge #6491 has everything settled. A review by Nadav is the only missing component.

**Comment by nyh** [comment]
I'm having a really hard time understand what is the actual problem reported in this issue, because it seems to have mutated and/or rethought through the different comments, and pull request 6491 also tries to explain a problem, but I didn't understand 1. what is exactly the *problem* (not just a description of what happens) and 2. how is it related to the issue in this bug, about an empty postimage?
If the comments in this issue are two irrelevant, maybe we need to close it an open a new issue which clearly explains what is actually wrong in the existing behavior?

**Comment by kbr-** [comment]
@nyh 

the issue reported by Aleks was that the post-image was calculated incorrectly.
As @jul-stas observed, this issue was fixed by @elcallio's patches.

However, a concurrent thread was started by @haaawk about collection inserts creating a lot of entries in the CDC log and there was a discussion whether or not we can improve it.
It turned out we can, and PR https://github.com/scylladb/scylla/pull/6491 simplifies splitting of collections.

---
So here's how Aleks' queries would turn out after https://github.com/scylladb/scylla/pull/6491 is merged.

without TTL:

```
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1} ;
cqlsh> CREATE TABLE ks.cf (pkey int, ckey int, value set<text>, PRIMARY KEY (pkey, ckey)) WITH cdc={'enabled': true, 'postimage': true};
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, { 'value1', 'value2'});
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, { 'value1', 'value2'});
cqlsh> select * from ks.cf_scylla_cdc_log ;

 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0xc78000000000000021a8e9c64d2bd361 | 66046b52-a721-11ea-43c4-659ed100641e |                0 |                       null |              True |             2 |    null |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 66046b52-a721-11ea-43c4-659ed100641e |                1 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 673e23a0-a721-11ea-bc86-6b89d7b20ef2 |                0 |                       null |              True |             2 |    null |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 673e23a0-a721-11ea-bc86-6b89d7b20ef2 |                1 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}

(4 rows)
```

with TTL:
```
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1} ;
cqlsh> CREATE TABLE ks.cf (pkey int, ckey int, value set<text>, PRIMARY KEY (pkey, ckey)) WITH cdc={'enabled': true, 'postimage': true};
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, { 'value1', 'value2'}) USING TTL 123;
cqlsh> INSERT INTO ks.cf (pkey, ckey, value) VALUES (1, 1, { 'value1', 'value2'}) USING TTL 123;
cqlsh> select * from ks.cf_scylla_cdc_log ;

 cdc$stream_id                      | cdc$time                             | cdc$batch_seq_no | cdc$deleted_elements_value | cdc$deleted_value | cdc$operation | cdc$ttl | ckey | pkey | value
------------------------------------+--------------------------------------+------------------+----------------------------+-------------------+---------------+---------+------+------+----------------------
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                0 |                       null |              null |             2 |     123 |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                1 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                2 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                3 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                4 |                       null |              null |             1 |     123 |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                5 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 8b4e6962-a721-11ea-6138-301f3a484715 |                0 |                       null |              null |             2 |     123 |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8b4e6962-a721-11ea-6138-301f3a484715 |                1 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 8b4e6962-a721-11ea-6138-301f3a484715 |                2 |                       null |              True |             1 |    null |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8b4e6962-a721-11ea-6138-301f3a484715 |                3 |                       null |              null |             9 |    null |    1 |    1 |                 null
 0xc78000000000000021a8e9c64d2bd361 | 8b4e6962-a721-11ea-6138-301f3a484715 |                4 |                       null |              null |             1 |     123 |    1 |    1 | {'value1', 'value2'}
 0xc78000000000000021a8e9c64d2bd361 | 8b4e6962-a721-11ea-6138-301f3a484715 |                5 |                       null |              null |             9 |    null |    1 |    1 | {'value1', 'value2'}

(12 rows)

```

looks good.

**Comment by aleksbykov** [comment]
@kbr- should all rows have ttl? because in the latest example for POSTIMAGE rows and for UPDATE rows the cdc$ttl is None

**Comment by kbr-** [comment]
`cdc$ttl` only makes sense for delta rows, I guess.

And there is no well-defined notion of TTL for deletions. Only for addition of cells. So for example:
```
 0xc78000000000000021a8e9c64d2bd361 | 8ac4801c-a721-11ea-54d0-c7f8cf7e0a47 |                2 |                       null |              True |             1 |    null |    1 |    1 |                 null
```
doesn't have a TTL.

**Comment by haaawk** [comment]
I agree with comment about deletions but ttl can be useful for preimage/postimage. TTL is part of the state of the row so it makes sense to include it into pre/post image.

**Comment by kbr-** [comment]
Saying that `cdc$ttl = X` in a post-image entry would suggest that all cells in this row have TTL `X`, which is not true in general. We don't know what TTL do the different cells end up with after applying the mutation, we only know it for the mutation that we're applying right now.

Same applies to pre-image.

**Comment by haaawk** [comment]
Fair enough. In such case we probably can close this issue.

**Comment by aleksbykov** [comment]
@kbr- , Thanks for clarification. then #6485 could be also closed

**Comment by nyh** [comment]
I'm at a loss here. @haaawk said "we can probably close this issue" and yet there seem to be here several threads of discussions I don't understand continuing, and the pull request https://github.com/scylladb/scylla/pull/6491 is still open and says it "fixes" this issue. Can someone who understand this issue please close it and perhaps replace it by a new issue if a part of this issue is still relevant?

**Comment by nyh** [comment]
Commit a1e235b which was marked as fixing this issue is already in branch 4.2. CDC is experimental, so not backporting to even older branches.
