### ISSUE TITLE
many named_semaphore_timed_out of smp_service_group caused the rebuild node is unavailable

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6127]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200320.df8b3cd5dc1
Cluster size: 6
loader number: 2
instance_type_db: 'i3.4xlarge'
OS (RHEL/CentOS/Ubuntu/AWS AMI): eu-west-1: ami-0386a4a8dc2086366

### Description:

Nemesis description:
- corrupt the data file on target node
- repair by 'nodetool repair' 
- interrupt 'nodetool repair' 
- rebuild data by 'nodetool rebuild'

Problem:
- rebuild completed (exit code: 0), but one node is unavailable during rebuild, it raised huge number of error - `storage_proxy - exception during mutation write to 10.0.4.111: sea
star::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 5->7 semaphore)`
- The compaction of target node which is rebuilt is very heavy

### db logs:
 https://cloudius-jenkins-test.s3.amazonaws.com/f2db583d-de47-4584-9ac9-04b7148ef4db/20200402_120627/db-cluster-f2db583d.zip

### Workloads:
 - cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)'
   cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100
 - cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)'
   cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100
 - cassandra-stress user no-warmup profile=/tmp/cdc_profile_postimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)'
   cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100
 - cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage_postimage.yaml
   ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m

[cdc_profiles.tar.gz](https://github.com/scylladb/scylla/files/4425664/cdc_profiles.tar.gz)

### Test info
- test id: f2db583d-de47-4584-9ac9-04b7148ef4db
- check grafana locally: hydra investigate show-monitor  f2db583d-de47-4584-9ac9-04b7148ef4db
- hydra investigate show-logs f2db583d-de47-4584-9ac9-04b7148ef4db
  - db logs | https://cloudius-jenkins-test.s3.amazonaws.com/f2db583d-de47-4584-9ac9-04b7148ef4db/20200402_120627/db-cluster-f2db583d.zip
  - sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/f2db583d-de47-4584-9ac9-04b7148ef4db/20200402_120627/sct-runner-f2db583d.zip
  - monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/f2db583d-de47-4584-9ac9-04b7148ef4db/20200402_120627/monitor-set-f2db583d.zip

Grafana snapshot: https://snapshot.raintank.io/dashboard/snapshot/upPMGKU68o5euvJUzkVkwvc1q9TFMkCx

![image](https://user-images.githubusercontent.com/309708/78334164-dd486780-75bd-11ea-8e6e-3b6e5b32a754.png)

![image](https://user-images.githubusercontent.com/309708/78334282-141e7d80-75be-11ea-9e71-2b65cdee91ba.png)

![image](https://user-images.githubusercontent.com/309708/78334754-e980f480-75be-11ea-9d3e-aaec96fee6e0.png)

### Nemesis:
- all nemesis finished.

```
04-02 08:11:10| >>>>> Started random_disrupt_method nodetool_drain
04-02 08:12:26| <<<<< Finished random_disrupt_method nodetool_drain
04-02 08:20:38| >>>>> Started random_disrupt_method add_drop_column
04-02 08:30:55| <<<<< Finished random_disrupt_method add_drop_column
04-02 08:38:14| >>>>> Started random_disrupt_method delete_by_rows_range
(skipped:  This nemesis can run on scylla_bench test only)
04-02 08:41:07| >>>>> Started random_disrupt_method stop_wait_start_scylla_server
04-02 08:48:04| <<<<< Finished random_disrupt_method stop_wait_start_scylla_server
04-02 08:55:54| >>>>> Started random_disrupt_method repair_streaming_err
04-02 11:17:51| <<<<< Finished random_disrupt_method repair_streaming_err
```

### key test logs with time stamp:
- there are many WriteTimeout before the `repair_streaming_err` nemesis
- rebuild totally executed 

```
< t:2020-04-02 08:29:42,998 f:remote.py       l:732  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.245.12]: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during UNLOGGED_BATCH write query at consistency QUORUM (2 replica were required but only 0 acknowledged the write)
the target node was restarted.

< t:2020-04-02 08:55:54,113 f:nemesis.py      l:647  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method repair_streaming_e
rr

### restart target node after corruptted the data

2020-04-02T08:58:50+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 !INFO    | scylla: [shard 0] storage_service - Starting listening for CQL clients on 10.0.4.111
:9042 (unencrypted)
2020-04-02T08:58:50+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 !INFO    | scylla: [shard 0] init - Scylla version 666.development-0.20200320.df8b3cd5dc1 initi
alization completed.
2020-04-02T08:59:35+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 !INFO    | scylla: [shard 0] repair - starting user-requested repair for keyspace system_auth, repair id 1, options {{ trace -> false}, { incremental -> false}, { jobThreads -> 1}, { primaryRange -> false}, { parallelism -> parallel}}
2020-04-02T08:59:35+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 !INFO    | scylla: [shard 0] repair - Repair 1 out of 766 ranges, id=1, shard=0, keyspace=system_auth, table={role_members, roles}, range=(-inf, 6781864413506381]


< t:2020-04-02 09:06:03,763 f:nemesis.py      l:1780 c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.ChaosMonkey: Interrupt the task by pkill

### rebuild
< t:2020-04-02 09:08:42,296 f:nemesis.py      l:1795 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: Recover the target node by a final rebuild
< t:2020-04-02 09:08:42,323 f:remote.py       l:305  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.4.111]: Running command "nodetool  rebuild "...

### rebuild completed (successfully)
< t:2020-04-02 11:17:51,175 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.4.111]: Command "nodetool  rebuild " finished with status
0
< t:2020-04-02 11:17:51,185 f:cluster.py      l:2417 c:sdcm.cluster_aws     p:DEBUG > Node longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 [52.215.57.98 | 10.0.4.111] (seed: False): Command 'nodetool  rebuild ' duration -> 7748.851637125015 s

< t:2020-04-02 11:17:51,193 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-02T11:15:47+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 !WARNING | scylla: [shard 6] storage_proxy - Failed to apply mutation from 10.0.178.6#6: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 2->6 semaphore)
< t:2020-04-02 11:17:51,185 f:remote.py       l:732  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.248.59]: com.datastax.driver.core.exceptions.OperationTimedOutException: [ip-10-0-4-111.eu-west-1.compute.internal/10.0.4.111:9042] Timed out waiting for server response

### Nemesis finished
< t:2020-04-02 11:17:51,200 f:nemesis.py      l:657  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.ChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method repair_streaming_err

< t:2020-04-02 11:17:51,208 f:cluster.py      l:1415 c:sdcm.cluster         p:DEBUG > 2020-04-02T11:15:47+00:00  longevity-cdc-100gb-4h-cdc-long-db-node-f2db583d-5 !WARNING
| scylla: [shard 6] storage_proxy - Failed to apply mutation from 10.0.178.6#6: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 2->6 semaphore)
```

@roydahan @slivne @haaawk

**Comment by haaawk** [comment]
If we failed to generate the right streams for some shards then CDC may increase the number of cross shards operations. We have a PR ready which makes us always generate the right streams and it may help with this issue: https://github.com/scylladb/scylla/pull/6117

**Comment by fgelcer** [comment]
i'm seeing very similar issue (in my case, the node is unavailable because it was terminated) 180K times.
10.0.56.93 is the node that was terminated.
```
< t:2020-04-06 16:57:55,779 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,779 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,782 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,783 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,785 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,785 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,788 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,791 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,791 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,791 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,792 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,792 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,792 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,792 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,793 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,793 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,793 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,794 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,795 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,795 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,795 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,796 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,796 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,796 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,797 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
< t:2020-04-06 16:57:55,797 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-06T16:57:50+00:00  longevity-tls-1tb-7d-4-0-db-node-bbc128f5-4 !WARNING | scylla: [shard 5] storage_proxy - Failed to apply mutation from 10.0.56.93#5: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 6->5 semaphore)
```

full logs to this run will be below:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: bbc128f5-0097-4db4-9327-d46c7d8e73a2                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/db-cluster-bbc128f5.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/monitor-set-bbc128f5.zip |
| loader-set  | None                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/bbc128f5-0097-4db4-9327-d46c7d8e73a2/20200412_105848/sct-runner-bbc128f5.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment]
Lets also validate https://github.com/scylladb/scylla/issues/6193

**Comment by amoskong** [comment]
It seems a general 'nodetool repair' also causes the `Semaphore timed out: smp_service_group`.
Just execute 'nodetool repair' on a db node.

Job: https://jenkins.scylladb.com/job/scylla-4.0/job/longevity/job/longevity-cdc-100gb-4h/15/
test id: 1bb14a1e-150f-4c0d-a6bb-6574cd025a39
test log: https://cloudius-jenkins-test.s3.amazonaws.com/1bb14a1e-150f-4c0d-a6bb-6574cd025a39/20200427_173551/sct-runner-1bb14a1e.zip
db log: https://cloudius-jenkins-test.s3.amazonaws.com/1bb14a1e-150f-4c0d-a6bb-6574cd025a39/20200427_173551/db-cluster-1bb14a1e.zip

At the end of NoCorruptRepair nemesis, a series of 'seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 10->12 semaphore)' raised. Repair finally finished successfully, but the schema check query failed, the query was executed on target node (db-node-1bb14a1e-4)

```
CMD: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "select peer, data_center, host_id, rack, release_version, rpc_address, schema_version, supported_features from system.peers" 10.0.198.22 9042'

Exit code: 1

Stderr: Connection error: ('Unable to connect to any servers', {'10.0.198.22': ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for system.peers - received only 0 responses from 1 CL=ONE." info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'}',)})
```

**Comment by slivne** [comment]
@amoskong / @fgelcer - are we hitting this on 4.1 - we had an issue in 4.0 with incorrect token that caused bad distribution of data (and it was fixed), I want to make sure we are hitting this post that fix.

**Comment by fgelcer** [comment]
> @amoskong / @fgelcer - are we hitting this on 4.1 - we had an issue in 4.0 with incorrect token that caused bad distribution of data (and it was fixed), I want to make sure we are hitting this post that fix.

@slivne , i'm missing something... what is the relation between those "named_semaphore_timed_out" and the bad data distribution?

**Comment by amoskong** [comment]
> @amoskong / @fgelcer - are we hitting this on 4.1 - we had an issue in 4.0 with incorrect token that caused bad distribution of data (and it was fixed), I want to make sure we are hitting this post that fix.

Yes, we can still see a lot of `!WARNING | scylla: [shard 1] storage_proxy - Failed to apply mutation from 10.0.223.182#1: seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 0->1 semaphore)` in the longevity-cdc-100gb-4h of 4.1.rc1

test id: 89aa4120-9057-4d7f-921d-3a9f330b99da
job link: https://jenkins.scylladb.com/job/scylla-4.1/job/longevity/job/longevity-cdc-100gb-4h/2/
db log: https://cloudius-jenkins-test.s3.amazonaws.com/89aa4120-9057-4d7f-921d-3a9f330b99da/20200530_052410/db-cluster-89aa4120.zip
version: 4.1.rc1-0.20200528.bb8fcbff68f
AMI: ami-00907d577946117dd (eu-west-1)

**Comment by slivne** [comment]
I am closing this issue - if this happens on 4.3 / 4.4 - please create a new issue related to rebuild

We are chasing issues related to eplace node operation in which we also have an issue with traffic dropping
