### ISSUE TITLE
dist: packages are broken

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#950]
trying to install  last night rpm's from repo fails

https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/master/26/scylla.repo

scylla-server-666.development-20160227.81bc5da.el7.centos.x86_64

```
Redirecting to /bin/systemctl status  scylla-server.service
● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Sun 2016-02-28 09:03:29 UTC; 3min 1s ago

Feb 28 09:03:28 ip-10-186-167-206 systemd[1]: scylla-server.service failed to run 'start-pre' task: Invalid argument
Feb 28 09:03:28 ip-10-186-167-206 systemd[1]: Failed to start Scylla Server.
Feb 28 09:03:28 ip-10-186-167-206 systemd[1]: Unit scylla-server.service entered failed state.
Feb 28 09:03:28 ip-10-186-167-206 systemd[1]: scylla-server.service failed.
Feb 28 09:03:28 ip-10-186-167-206 systemd[1]: Starting Scylla Server...
Feb 28 09:03:29 ip-10-186-167-206 systemd[1]: scylla-server.service holdoff time over, scheduling restart.
Feb 28 09:03:29 ip-10-186-167-206 systemd[1]: start request repeated too quickly for scylla-server.service
Feb 28 09:03:29 ip-10-186-167-206 systemd[1]: Failed to start Scylla Server.
Feb 28 09:03:29 ip-10-186-167-206 systemd[1]: Unit scylla-server.service entered failed state.
Feb 28 09:03:29 ip-10-186-167-206 systemd[1]: scylla-server.service failed.
```

I think the issue is in the EnvironmentFile definition 
```
[centos@ip-10-186-167-206 ~]$ cat /usr/lib/systemd/system/scylla-server.service
[Unit]
Description=Scylla Server
After=network.target

[Service]
Type=notify
LimitMEMLOCK=infinity
LimitNOFILE=200000
LimitAS=infinity
LimitNPROC=8096
WorkingDirectory=/var/lib/scylla
Environment="HOME=/var/lib/scylla"
EnvironmentFile=/etc/sysconfig/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
ExecStartPre=/usr/bin/sudo -E /usr/lib/scylla/scylla_prepare
ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SCYLLA_IO
ExecStopPost=/usr/bin/sudo -E /usr/lib/scylla/scylla_stop
TimeoutStartSec=900
KillMode=process
Restart=on-abnormal
User=scylla

[Install]
WantedBy=multi-user.target
```

ls /etc/scylla.d/*.conf - no file exists

if i remove this line and issue ```sudo systemctl daemon-reload```

scylla is able to start

**Comment by syuu1228** [comment]
The entry was for io,conf, and it should created by scylla-io-setup.service, I think real problem is dependency definition between scylla-io-setup.service and scylla-server.service. Will fix soon.

**Comment by penberg** [comment]
Is this fixed by https://github.com/scylladb/scylla/commit/84447fd7b075fe542af56acc826a368459504559?

**Comment by syuu1228** [comment]
@penberg It fixes scylla-io-setup.service bug, but works only when user executed "systemctl enable scylla-io-setup.service". Otherwise "systemctl start scylla-server" still fail. Sent new patchset for this.
